// src/components/reports/ReportFooter.tsx
import React from "react";
import { getBSTodayLong } from "../../lib/nepaliDate";

interface ReportFooterProps {
  currentUser?: string;
  // For print: these are set automatically
  screenMode?: "always" | "print-only";
}

const ReportFooter: React.FC<ReportFooterProps> = ({
  currentUser = "System",
  screenMode = "print-only",
}) => {
  const isAlwaysVisible = screenMode === "always";

  let bsDateStr = "";
  let adDateStr = "";
  try {
    bsDateStr = getBSTodayLong();
    adDateStr = new Date().toLocaleDateString("en-IN", {
      day: "2-digit",
      month: "short",
      year: "numeric",
    });
  } catch {
    adDateStr = new Date().toLocaleDateString();
  }

  return (
    <div
      className={isAlwaysVisible ? "" : "print-only hidden"}
      style={{
        borderTop: "1px solid #d1d5db",
        paddingTop: 8,
        marginTop: 16,
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        fontSize: 10,
        color: "#9ca3af",
        flexWrap: "wrap",
        gap: 8,
      }}
    >
      {/* Left: printed by + date */}
      <div>
        Printed by: <span style={{ color: "#374151", fontWeight: 600 }}>{currentUser}</span>
        &nbsp;on&nbsp;
        <span style={{ color: "#374151" }}>{bsDateStr}</span>
        &nbsp;({adDateStr})
      </div>

      {/* Center: page counter — uses CSS @page counter in print */}
      <div
        className="page-counter"
        style={{ textAlign: "center" }}
      >
        {/* This text is replaced by CSS counter in print */}
        Page <span className="page-number-current" /> of{" "}
        <span className="page-number-total" />
      </div>

      {/* Right: software name */}
      <div>
        Generated by{" "}
        <span style={{ color: "#1557b0", fontWeight: 600 }}>Sutra ERP</span>
        {" "}v2.0
      </div>
    </div>
  );
};

export default ReportFooter;
