#!/usr/bin/env python3
"""Generate Ollama Modelfile with e-Khata CA system prompt."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

BOT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BOT_ROOT / "src"))

from khata.system_prompt import KHATA_SYSTEM_PROMPT  # noqa: E402


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--base", default="qwen2.5:7b-instruct")
    parser.add_argument("--output", default="Modelfile.generated")
    parser.add_argument("--merged-path", default="")
    args = parser.parse_args()

    base = args.base
    if args.merged_path and Path(args.merged_path).exists():
        base = args.merged_path

    # Escape for Modelfile SYSTEM block
    system = KHATA_SYSTEM_PROMPT.replace('"""', '\\"\\"\\"')

    content = f"""# e-Khata CA Brain — generated by export_to_ollama.sh
FROM {base}

SYSTEM \"\"\"
{system}

## Structured Entry Output
When user describes a transaction and rules cannot parse it, output JSON:
{{"intent":"khata_*","amount":N,"party":"...","journalLines":[...]}}
Never invent amounts. Always balance debits and credits.
\"\"\"

PARAMETER temperature 0.35
PARAMETER num_ctx 8192
PARAMETER stop "<|im_start|>"
PARAMETER stop ""
"""

    out = Path(__file__).parent / args.output
    out.write_text(content, encoding="utf-8")
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
