import { CommandPaletteItem } from "./menuTypes";

export const COMMAND_ITEMS: CommandPaletteItem[] = [
  {
    id: "cmd-dashboard",
    label: "Dashboard",
    page: "dashboard",
    category: "Dashboard",
    description: "Open business dashboard",
    shortcut: "Ctrl+D",
  },
  {
    id: "cmd-accounts",
    label: "Chart of Accounts",
    page: "accounts",
    category: "Masters",
    description: "Ledgers and account groups",
    shortcut: "Ctrl+A",
  },
  {
    id: "cmd-parties",
    label: "Parties Directory",
    page: "parties",
    category: "Masters",
    description: "Customers and suppliers",
    shortcut: "Ctrl+P",
  },
  {
    id: "cmd-items",
    label: "Stock Book",
    page: "items",
    category: "Masters",
    description: "Stock items and inventory master",
  },
  {
    id: "cmd-sales",
    label: "Sales Invoice",
    page: "billing",
    category: "Transactions",
    description: "Create VAT sales invoice",
    shortcut: "Ctrl+I",
  },
  {
    id: "cmd-purchase",
    label: "Purchase Invoice",
    page: "purchase-invoice",
    category: "Transactions",
    description: "Create purchase invoice",
  },
  {
    id: "cmd-payment",
    label: "Payment Voucher",
    page: "payment",
    category: "Transactions",
    description: "Record payment voucher",
  },
  {
    id: "cmd-receipt",
    label: "Receipt Voucher",
    page: "receipt",
    category: "Transactions",
    description: "Record receipt voucher",
  },
  {
    id: "cmd-journal",
    label: "Journal Voucher",
    page: "journal",
    category: "Transactions",
    description: "Double-entry journal entry",
  },
  {
    id: "cmd-vouchers",
    label: "Vouchers Register",
    page: "vouchers",
    category: "Transactions",
    description: "View all vouchers",
  },
  {
    id: "cmd-trial",
    label: "Trial Balance",
    page: "trial-balance",
    category: "Reports",
    description: "View trial balance",
    shortcut: "Ctrl+T",
  },
  {
    id: "cmd-bs",
    label: "Balance Sheet",
    page: "balance-sheet",
    category: "Reports",
    description: "View balance sheet",
    shortcut: "Ctrl+B",
  },
  {
    id: "cmd-pl",
    label: "Profit & Loss",
    page: "profit-loss",
    category: "Reports",
    description: "View P&L report",
  },
  {
    id: "cmd-ledger",
    label: "General Ledger",
    page: "ledger",
    category: "Reports",
    description: "Open ledger report",
  },
  {
    id: "cmd-daybook",
    label: "Day Book",
    page: "day-book",
    category: "Reports",
    description: "Daily transaction register",
  },
  {
    id: "cmd-vat",
    label: "VAT Reports",
    page: "vat-reports",
    category: "Tax",
    description: "Nepal VAT annex reports",
  },
  {
    id: "cmd-tds",
    label: "TDS Report",
    page: "tds-report",
    category: "Tax",
    description: "Withholding tax report",
  },
  {
    id: "cmd-bank-reco",
    label: "Bank Reconciliation",
    page: "bank-reconciliation",
    category: "Banking",
    description: "Reconcile bank statement",
  },
  {
    id: "cmd-company-features",
    label: "Company Features",
    page: "company-features",
    category: "Company",
    description: "Enable modules for Nepal accounting",
    shortcut: "F11",
  },
  {
    id: "cmd-company-select",
    label: "Select Company",
    page: "company-selector",
    category: "Company",
    description: "Open another company",
    shortcut: "F3",
  },
  {
    id: "cmd-backup",
    label: "Backup",
    page: "backup",
    category: "Data",
    description: "Backup company data",
  },
  {
    id: "cmd-cloud-backup",
    label: "Cloud Backup",
    page: "cloud-backup",
    category: "Data",
    description: "Configure cloud backup",
  },
  {
    id: "cmd-import-masters",
    label: "Import Masters",
    page: "import-masters",
    category: "Actions",
    description: "Import ledgers, parties, items",
  },
  {
    id: "cmd-import-transactions",
    label: "Import Transactions",
    page: "import-transactions",
    category: "Actions",
    description: "Import vouchers",
  },
  {
    id: "cmd-export-logs",
    label: "Export Logs",
    page: "export-logs",
    category: "Actions",
    description: "View export history",
  },
  {
    id: "cmd-print-logs",
    label: "Print Logs",
    page: "print-logs",
    category: "Actions",
    description: "View print history",
  },
  {
    id: "cmd-help",
    label: "Help",
    page: "help",
    category: "Help",
    description: "Open help center",
    shortcut: "F1",
  },
  {
    id: "cmd-troubleshoot",
    label: "Troubleshoot",
    page: "troubleshoot",
    category: "Help",
    description: "Diagnostics and repair tools",
  },
];
