import { ScreenCapability } from "./menuTypes";

const TITLE_MAP: Record<string, string> = {
  dashboard: "Dashboard",
  accounts: "Chart of Accounts",
  parties: "Parties Directory",
  items: "Stock Book",
  billing: "Billing Invoice",
  "sales-invoice": "Sales Invoice",
  "purchase-invoice": "Purchase Invoice",
  "sales-return": "Sales Return",
  "purchase-return": "Purchase Return",
  payment: "Payment Voucher",
  receipt: "Receipt Voucher",
  journal: "Journal Voucher",
  contra: "Contra Voucher",
  "debit-note": "Debit Note",
  "credit-note": "Credit Note",
  vouchers: "Vouchers Register",
  ledger: "General Ledger",
  "trial-balance": "Trial Balance",
  "balance-sheet": "Balance Sheet",
  "profit-loss": "Profit & Loss",
  "cash-flow": "Cash Flow Statement",
  "day-book": "Day Book",
  "cash-book": "Cash Book",
  "bank-book": "Bank Book",
  "sales-register": "Sales Register",
  "purchase-register": "Purchase Register",
  "stock-summary": "Stock Summary",
  "inventory-report": "Inventory Report",
  "vat-reports": "VAT Reports",
  "tds-report": "TDS Report",
  "bank-reconciliation": "Bank Reconciliation",
  "cost-center-report": "Cost Center Report",
  "company-features": "Company Features",
};

const EXPORTABLE = new Set([
  "accounts",
  "parties",
  "items",
  "billing",
  "sales-invoice",
  "purchase-invoice",
  "sales-return",
  "purchase-return",
  "payment",
  "receipt",
  "journal",
  "contra",
  "debit-note",
  "credit-note",
  "vouchers",
  "ledger",
  "trial-balance",
  "balance-sheet",
  "profit-loss",
  "cash-flow",
  "day-book",
  "cash-book",
  "bank-book",
  "sales-register",
  "purchase-register",
  "stock-summary",
  "inventory-report",
  "vat-reports",
  "tds-report",
  "bank-reconciliation",
  "cost-center-report",
]);

const PRINTABLE = new Set([
  "billing",
  "sales-invoice",
  "purchase-invoice",
  "sales-return",
  "purchase-return",
  "payment",
  "receipt",
  "journal",
  "contra",
  "debit-note",
  "credit-note",
  "vouchers",
  "ledger",
  "trial-balance",
  "balance-sheet",
  "profit-loss",
  "cash-flow",
  "day-book",
  "cash-book",
  "bank-book",
  "sales-register",
  "purchase-register",
  "stock-summary",
  "vat-reports",
  "tds-report",
]);

const SHAREABLE = new Set([
  "billing",
  "sales-invoice",
  "purchase-invoice",
  "sales-return",
  "purchase-return",
  "vouchers",
  "ledger",
  "trial-balance",
  "balance-sheet",
  "profit-loss",
  "sales-register",
  "purchase-register",
  "stock-summary",
  "vat-reports",
  "tds-report",
]);

export function getScreenCapability(currentPage: string): ScreenCapability {
  return {
    currentPage,
    title:
      TITLE_MAP[currentPage] ||
      currentPage
        .replace(/-/g, " ")
        .replace(/\b\w/g, (char) => char.toUpperCase()),
    canExport: EXPORTABLE.has(currentPage),
    canPrint: PRINTABLE.has(currentPage),
    canShare: SHAREABLE.has(currentPage),
    documentType: TITLE_MAP[currentPage] || currentPage,
  };
}
