"""e-Khata conversational LLM via Ollama — all replies generated by the model."""

from __future__ import annotations

import json
import re
from datetime import date
from typing import Any

from langchain_core.messages import AIMessage, HumanMessage, SystemMessage
from langchain_ollama import ChatOllama

from ..config import KHATA_STRUCTURED_PARSE, MODEL_NAME, OLLAMA_BASE_URL
from ..falcon_trader import parse_khata_message
from .context_intelligence import (
    MessageKind,
    build_intelligent_context,
    classify_message_kind,
    clear_session_context,
    update_session_from_card,
    update_session_from_message,
)
from .structured_parse import STRUCTURED_PARSE_INSTRUCTION, parse_llm_response
from .system_prompt import KHATA_SYSTEM_PROMPT

_sessions: dict[str, list] = {}
_MAX_HISTORY = 24

_llm = ChatOllama(
    model=MODEL_NAME,
    base_url=OLLAMA_BASE_URL,
    temperature=0.35,
    num_ctx=2048,
    num_predict=400,
)

_concept_llm = ChatOllama(
    model=MODEL_NAME,
    base_url=OLLAMA_BASE_URL,
    temperature=0.12,
    num_ctx=2048,
    num_predict=280,
)


def _detect_language(text: str, hint: str | None = None) -> str:
    if hint in ("nepali", "english", "mixed"):
        return hint
    en = len(re.findall(
        r"\b(the|is|are|what|how|entry|debit|credit|account|journal|asset|liability)\b",
        text, re.I,
    ))
    ne = len(re.findall(
        r"\b(k\s*ho|kasari|udhaar|kharcha|bikri|tiryo|hisab|lekha|chha|hunchha)\b|[\u0900-\u097F]",
        text, re.I,
    ))
    if en > ne * 1.5:
        return "english"
    if ne > en * 1.5:
        return "nepali"
    return "mixed"


def _parsed_to_card(parsed: dict[str, Any], raw_text: str) -> dict[str, Any] | None:
    intent = parsed.get("intent")
    amount = parsed.get("AMOUNT")
    if not intent or not amount:
        return None
    card: dict[str, Any] = {
        "intent": intent,
        "party": None if parsed.get("PARTY") in (None, "UNKNOWN") else parsed.get("PARTY"),
        "amount": int(amount),
        "item": parsed.get("ITEM"),
        "date": parsed.get("DATE") or date.today().isoformat(),
        "raw_text": raw_text,
    }
    if parsed.get("journal_lines"):
        card["journalLines"] = parsed["journal_lines"]
    if parsed.get("ca_explanation"):
        card["caExplanation"] = parsed["ca_explanation"]
    return card


def _journal_balanced(card: dict[str, Any]) -> bool:
    lines = card.get("journalLines") or []
    if not lines:
        return True
    total_dr = sum(float(l.get("debit", 0) or 0) for l in lines)
    total_cr = sum(float(l.get("credit", 0) or 0) for l in lines)
    return abs(total_dr - total_cr) <= 0.02


def _balance_block(balance: dict[str, Any] | None) -> str:
    if not balance:
        return ""
    out = balance.get("udhaar_out")
    inn = balance.get("udhaar_in")
    if out is None and inn is None:
        return ""
    return (
        f"\n\n[CURRENT KHATA BALANCE]\n"
        f"Udharo baahir (receivable): NPR {int(out or 0):,}\n"
        f"Udharo bhitra (payable): NPR {int(inn or 0):,}"
    )


def _lang_instruction(lang: str) -> str:
    if lang == "english":
        return "\n\n[LANGUAGE] User writes in English. Reply in English."
    if lang == "nepali":
        return "\n\n[LANGUAGE] User writes in Nepali. Reply in Nepali (Roman or Devanagari matching user)."
    return "\n\n[LANGUAGE] User uses mixed Nepali/English. Match their style."


def _invoke_llm(
    message: str,
    session_id: str,
    balance: dict[str, Any] | None,
    lang: str,
    context: str = "",
    extra_instruction: str = "",
    *,
    concept_mode: bool = False,
) -> str:
    history = _sessions.setdefault(session_id, [])
    system = KHATA_SYSTEM_PROMPT + _balance_block(balance) + _lang_instruction(lang)
    if context:
        system += f"\n\n[CONTEXT]\n{context}"
    if extra_instruction:
        system += f"\n\n[INSTRUCTION]\n{extra_instruction}"

    messages = [SystemMessage(content=system)]
    messages.extend(history[-_MAX_HISTORY:])
    messages.append(HumanMessage(content=message))

    model = _concept_llm if concept_mode else _llm
    try:
        result = model.invoke(messages)
        text = result.content if hasattr(result, "content") else str(result)
    except Exception as exc:
        if lang == "english":
            return f"Could not connect to Ollama: {exc}. Start `ollama serve` and erp_bot."
        return f"Ollama sanga jodna sakina: {exc}. `ollama serve` ra erp_bot start garnus."

    history.append(HumanMessage(content=message))
    history.append(AIMessage(content=text))
    if len(history) > _MAX_HISTORY:
        _sessions[session_id] = history[-_MAX_HISTORY:]

    return text.strip()


def _is_transaction_signal(text: str) -> bool:
    """Heuristic gate — only used to decide whether to attempt structured parse, not reply text."""
    return bool(re.search(
        r"\b(\d+|saya|hajar|lakh)\b.*\b(udhaar|salary|ssf|gratuity|vat|tds|"
        r"depreciation|bad\s*debt|loan|capital|drawings|stock|kharcha|bikri|kineko|kinyo|"
        r"tiryo|diyo|becheko|sold|purchase|bought|payment|commission|advance|return|rent|bhaada)\b",
        text, re.I,
    )) or bool(re.search(r"\b(sold|bought|paid|received|tiryo|kineko|kinyo)\b.*\d", text, re.I))


def _try_llm_structured_parse(
    text: str,
    session_id: str,
    balance: dict[str, Any] | None,
    lang: str,
    context: str,
) -> tuple[dict[str, Any] | None, str | None]:
    """LLM JSON extraction for transactions the regex parser missed."""
    if not KHATA_STRUCTURED_PARSE:
        return None, None

    parse_ctx = STRUCTURED_PARSE_INSTRUCTION + "\n\nReturn JSON only for this transaction:\n" + text
    history = _sessions.setdefault(session_id, [])
    system = (
        KHATA_SYSTEM_PROMPT
        + _balance_block(balance)
        + _lang_instruction(lang)
        + (f"\n\n[CONTEXT]\n{context}" if context else "")
        + f"\n\n[INSTRUCTION]\n{parse_ctx}"
    )
    messages = [SystemMessage(content=system)]
    messages.extend(history[-_MAX_HISTORY:])
    messages.append(HumanMessage(content=text))

    try:
        result = _llm.invoke(messages)
        raw = result.content if hasattr(result, "content") else str(result)
    except Exception:
        return None, None

    card, clarify = parse_llm_response(raw, text)
    return card, clarify


def _entry_instruction(card: dict[str, Any], lang: str) -> str:
    lang_label = "English" if lang == "english" else "Nepali"
    return (
        f"A journal entry was extracted from the user's message. "
        f"Parsed data (DO NOT change amounts): {json.dumps(card, ensure_ascii=False)}. "
        f"Explain the Dr/Cr entry in {lang_label} and ask the user to click Confirm if correct."
    )


def _clarify_instruction(hint: str | None) -> str:
    base = (
        "The transaction is ambiguous or missing details. "
        "Ask the user ONE clear clarifying question in their language."
    )
    if hint:
        return f"{base}\nParser hint (use as guidance, not verbatim): {hint}"
    return base


def _concept_instruction(context: str) -> str:
    return (
        "ACCOUNTING DEFINITION QUESTION — answer in 2-4 sentences.\n"
        "1. First sentence: state the IFRS definition from the paragraphs below.\n"
        "2. Cite Para number(s) (e.g. Para 4.3).\n"
        "3. Use the user's language (Nepali/English as they wrote).\n"
        "4. Do NOT ask clarifying questions, list interpretations, or discuss grammar.\n\n"
        "IFRS paragraphs to use:\n"
        f"{context[:3500]}"
    )


def khata_chat(
    message: str,
    session_id: str,
    balance: dict[str, Any] | None = None,
    language: str | None = None,
) -> dict[str, Any]:
    """All user-facing replies are generated by the LLM with retrieved semantic context."""
    text = (message or "").strip()
    lang = _detect_language(text, language)

    update_session_from_message(session_id, text)
    msg_kind = classify_message_kind(text)
    context = build_intelligent_context(text, session_id)

    if not text:
        reply = _invoke_llm(
            "(empty message)",
            session_id,
            balance,
            lang,
            context=context,
            extra_instruction="The user sent an empty message. Briefly prompt them to ask about accounting entries or concepts.",
        )
        return {"kind": "chat", "reply": reply, "card": None, "session_id": session_id, "engine": "ollama"}

    # Regex parser — structured extraction only, never generates reply text
    parsed = parse_khata_message(text)

    if parsed.get("clarifying_question"):
        reply = _invoke_llm(
            text,
            session_id,
            balance,
            lang,
            context=context,
            extra_instruction=_clarify_instruction(str(parsed["clarifying_question"])),
        )
        return {
            "kind": "clarify",
            "reply": reply,
            "card": None,
            "session_id": session_id,
            "engine": "ollama",
        }

    card = _parsed_to_card(parsed, text)
    if card and _journal_balanced(card):
        update_session_from_card(session_id, card)
        reply = _invoke_llm(
            text,
            session_id,
            balance,
            lang,
            context=context,
            extra_instruction=_entry_instruction(card, lang),
        )
        return {
            "kind": "entry",
            "reply": reply,
            "card": card,
            "session_id": session_id,
            "engine": "ollama",
        }

    # LLM structured parse fallback — only for transaction-like messages regex missed
    llm_card, llm_clarify = None, None
    if _is_transaction_signal(text):
        llm_card, llm_clarify = _try_llm_structured_parse(text, session_id, balance, lang, context)
    if llm_clarify:
        reply = _invoke_llm(
            text,
            session_id,
            balance,
            lang,
            context=context,
            extra_instruction=_clarify_instruction(llm_clarify),
        )
        return {
            "kind": "clarify",
            "reply": reply,
            "card": None,
            "session_id": session_id,
            "engine": "ollama",
        }
    if llm_card and _journal_balanced(llm_card):
        update_session_from_card(session_id, llm_card)
        reply = _invoke_llm(
            text,
            session_id,
            balance,
            lang,
            context=context,
            extra_instruction=_entry_instruction(llm_card, lang),
        )
        return {
            "kind": "entry",
            "reply": reply,
            "card": llm_card,
            "session_id": session_id,
            "engine": "ollama",
        }

    # General conversation, definitions, IFRS/NAS Q&A — LLM with retrieved context
    concept_extra = _concept_instruction(context) if msg_kind == MessageKind.ACCOUNTING_CONCEPT else ""
    reply = _invoke_llm(
        text,
        session_id,
        balance,
        lang,
        context="" if msg_kind == MessageKind.ACCOUNTING_CONCEPT else context,
        extra_instruction=concept_extra,
        concept_mode=msg_kind == MessageKind.ACCOUNTING_CONCEPT,
    )
    return {
        "kind": "chat",
        "reply": reply,
        "card": None,
        "session_id": session_id,
        "engine": "ollama",
    }


def clear_session(session_id: str) -> None:
    _sessions.pop(session_id, None)
    clear_session_context(session_id)
