#!/usr/bin/env python3
"""Replace placeholder Nepal AI knowledge/regulated batches 21–27, 35–39 with quality data."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
REG = ROOT / "data" / "nepal-ai" / "regulated"
KNOW = ROOT / "data" / "nepal-ai" / "knowledge"
LANG = ROOT / "data" / "nepal-ai" / "language"

TAX_DISCLAIMER = "Rates and rules change. Consult CA or IRD for current applicable rules."
LEGAL_DISCLAIMER = "Legal matters are case-specific. Consult a licensed lawyer."
LABOR_DISCLAIMER = "Rules update frequently. Verify with official SSF/Labour notices and CA."

def write_jsonl(path: Path, rows: list[dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")


def tax_row(term, nepali, roman, meaning, rates="Verify with IRD"):
    return {
        "term": term, "nepali": nepali, "roman": roman, "meaning_en": meaning,
        "current_rates_general": rates,
        "common_questions": [f"{term} k ho?", f"{term} kasari file garne?", f"{term} kati %?"],
        "risk_level": "high", "disclaimer_required": True, "disclaimer": TAX_DISCLAIMER,
    }


def tax_vocab() -> list[dict]:
    return [
        tax_row("VAT", "मूल्य अभिवृद्धि कर", "mulya abhivriddhi kar", "Value Added Tax on taxable supplies in Nepal"),
        tax_row("input VAT", "इनपुट भ्याट", "input VAT", "VAT paid on purchases — claimable against output VAT subject to rules"),
        tax_row("output VAT", "आउटपुट भ्याट", "output VAT", "VAT collected on sales — payable to IRD after set-off"),
        tax_row("VAT return", "भ्याट फिर्ता", "VAT return", "Periodic VAT filing (usually monthly) through IRD portal"),
        tax_row("VAT bill", "कर बिल", "kar bill", "Tax invoice with PAN, amount, VAT breakdown for registered taxpayers"),
        tax_row("zero rated", "शून्य दर", "shunya dar", "Supplies taxed at 0% — input VAT may still be claimable"),
        tax_row("exempt supply", "छुट प्रदाय", "chhut praday", "Supplies outside VAT — generally no input VAT credit"),
        tax_row("reverse charge", "रिभर्स चार्ज", "reverse charge", "Recipient accounts for VAT on specified imports/services"),
        tax_row("PAN", "स्थायी लेखा नम्बर", "sthayi lekha number", "Permanent Account Number for tax registration"),
        tax_row("TDS", "स्रोतमा कर कट्टी", "srot ma kar katti", "Tax Deducted at Source — payer withholds before payment",
                "Goods ~1.5%, services ~10%, rent ~15% — verify IRD"),
        tax_row("income tax", "आयकर", "aayakar", "Tax on income of persons and entities"),
        tax_row("tax slab", "कर दर तालिका", "kar dar talika", "Progressive income tax brackets for individuals"),
        tax_row("presumptive tax", "अनुमानित कर", "anumanit kar", "Simplified tax for small turnover businesses"),
        tax_row("advance tax", "अग्रिम कर", "agrim kar", "Quarterly advance income tax payments"),
        tax_row("withholding tax", "कट्टी कर", "katti kar", "Tax withheld at source on payments"),
        tax_row("ETDS", "इलेक्ट्रोनिक टिडিএस", "electronic TDS", "Online TDS filing and payment system"),
        tax_row("income tax return", "आयकर फिर्ता", "aayakar firta", "Annual income tax declaration and payment"),
        tax_row("audit threshold", "लेखा परीक्षण सीमा", "lekha parikshan sima", "Turnover above which statutory audit may be required"),
        tax_row("tax clearance", "कर चुक्ता प्रमाणपत्र", "kar chukta pramanpatra", "Certificate showing tax liabilities settled"),
        tax_row("annex 13", "अनुसूची १३", "anusuchi 13", "TDS return annex — verify current IRD form"),
        tax_row("form 13", "फारम १३", "form 13", "Withholding tax certificate / related compliance form"),
        tax_row("late filing fee", "ढिलो दाखिला जरिवाना", "dhilo dakhila jarivana", "Penalty for missing filing deadline"),
        tax_row("surcharge", "अधिभार", "adhibhar", "Additional levy on unpaid tax"),
        tax_row("interest on tax", "कर ब्याज", "kar byaj", "Interest on delayed tax payment"),
        tax_row("blacklist", "कालोसूची", "kalosuchi", "IRD list of non-compliant taxpayers"),
        tax_row("excise duty", "उत्पादन शुल्क", "utpadan shulk", "Duty on specified goods — separate from VAT"),
        tax_row("customs duty", "भन्सार शुल्क", "bhansar shulk", "Import duty at customs"),
        tax_row("tax invoice", "कर इन्भ्वाइस", "kar invoice", "Invoice meeting VAT Act requirements"),
        tax_row("credit note", "क्रेडिट नोट", "credit note", "Reduces output VAT / sales after return"),
        tax_row("debit note", "डेबिट नोट", "debit note", "Adjusts purchase / input VAT"),
        tax_row("fiscal year Nepal", "आर्थिक वर्ष", "arthik barsa", "Shrawan 1 to Ashadh end — Nepal fiscal year"),
        tax_row("IRD", "आन्तरिक राजस्व विभाग", "aantarik rajaswa bibhag", "Inland Revenue Department — tax authority"),
        tax_row("VAT registration", "भ्याट दर्ता", "VAT darta", "Mandatory above turnover threshold for taxable business"),
        tax_row("exempt turnover", "छुट कारोबार", "chhut karobar", "Turnover below VAT registration threshold"),
        tax_row("export VAT", "निर्यात भ्याट", "niryat VAT", "Zero-rated exports — special documentation"),
        tax_row("import VAT", "आयात भ्याट", "aayat VAT", "VAT on imports — often at customs"),
        tax_row("entertainment tax", "मनोरञ्जन कर", "manoranjan kar", "Local/sector specific taxes — verify municipality"),
        tax_row("rent tax TDS", "भाडा कर कट्टी", "bhada kar katti", "TDS on rent payments to landlords"),
        tax_row("professional tax", "व्यावसायिक कर", "byabasayik kar", "Tax on professional income — verify category"),
        tax_row("capital gains tax", "पूँजीगत लाभ कर", "punjigat labh kar", "Tax on gain from asset disposal"),
    ]


def legal_row(term, nepali, meaning, process):
    return {
        "term": term, "nepali": nepali, "meaning_en": meaning, "process_overview": process,
        "common_questions": [f"{term} k ho?", f"{term} kasari garne?"],
        "risk_level": "high", "disclaimer_required": True, "disclaimer": LEGAL_DISCLAIMER,
    }


def legal_vocab() -> list[dict]:
    terms = [
        ("lalpurja", "लालपुर्जा", "Land ownership certificate in Nepal", "Malpot office — transfer via naamsari/baandapatra"),
        ("naamsari", "नामसारी", "Transfer of land ownership title", "Malpot application, tax clearance, witness, registration fee"),
        ("baandapatra", "बन्दापत्र", "Mortgage/lien registered on property", "Bank and Malpot process to register security"),
        ("karar", "करार", "Contract/agreement between parties", "Written terms, stamp duty, signatures, witnesses"),
        ("MOU", "समझौता ज्ञापन", "Memorandum of Understanding — non-binding intent", "Used before formal contract"),
        ("agreement", "सम्झौता", "Binding contract", "Define scope, payment, dispute resolution"),
        ("sarbochcha adalat", "सर्वोच्च अदालत", "Supreme Court of Nepal", "Final appellate court"),
        ("uchcha adalat", "उच्च अदालत", "High Court — appellate jurisdiction", "Appeals from district courts"),
        ("jilla adalat", "जिल्ला अदालत", "District Court — trial court", "Civil and criminal trials"),
        ("nyayalaya", "न्यायालय", "Court / judiciary", "Generic term for courts"),
        ("wakil", "वकिल", "Licensed advocate/lawyer", "Represents clients in legal matters"),
        ("mudda", "मुद्दा", "Court case/lawsuit", "Civil or criminal proceeding"),
        ("fir", "प्रथम सूचना रिपोर्ट", "First Information Report — police complaint", "Criminal case initiation"),
        ("company registration", "कम्पनी दर्ता", "Registering Pvt Ltd/PLC at OCR", "MOIC/OCR — memorandum, articles, capital"),
        ("OCR", "कम्पनी रजistrarको कार्यालय", "Office of Company Registrar", "Company incorporation and filings"),
        ("share transfer", "शेयर हस्तान्तरण", "Transfer of company shares", "Board resolution, share register update"),
        ("AGM", "वार्षिक साधारण सभा", "Annual General Meeting", "Companies Act compliance"),
        ("board resolution", "संचालक समिति निर्णय", "Formal board decision", "Required for major company actions"),
        ("stamp duty", "टाँच", "Tax on documents/contracts", "Varies by transaction type"),
        ("power of attorney", "वकिलनामा", "Legal authority to act for another", "Notarized document"),
        ("arbitration", "मध्यस्थता", "Dispute resolution outside court", "Faster commercial dispute forum"),
        ("mediation", "मेलमिलाप", "Negotiated settlement with mediator", "Alternative dispute resolution"),
        ("breach of contract", "करार उल्लंघन", "Failure to perform contractual obligations", "May lead to damages claim"),
        ("damages", "हर्जाना", "Monetary compensation for loss", "Civil remedy"),
        ("injunction", "रोक्का", "Court order to stop an action", "Interim relief"),
        ("bail", "धरौटी", "Security for release from custody", "Criminal procedure"),
        ("probation period", "परिवीक्षा अवधि", "Trial employment period", "Labour relation — notice rules apply"),
        ("termination", "बर्खास्त", "Ending employment contract", "Must follow Labour Act notice/severance"),
        ("notice period", "सूचना अवधि", "Advance notice before leaving/termination", "Labour Act minimums"),
        ("non-compete", "प्रतिस्पर्धा नगर्ने", "Restriction on competing after exit", "Enforceability limited — legal review"),
        ("intellectual property", "बौद्धिक सम्पत्ति", "Trademarks, patents, copyright", "DOI registration in Nepal"),
        ("trademark", "व्यापार चिन्ह", "Brand mark registration", "Department of Industry"),
        ("partnership deed", "साझेदारी दस्तावेज", "Agreement between business partners", "Profit share, capital, dispute"),
        ("dissolution", "विघटन", "Closing a company/partnership", "OCR/IRD clearance, creditor settlement"),
        ("insolvency", "दivālā", "Unable to pay debts", "Insolvency Act proceedings"),
        ("cheque dishonor", "चेक बाउन्स", "Dishonored cheque — NI Act", "Criminal/civil remedies possible"),
        ("NI Act", "नेगोसिएबल इन्स्ट्रुमेन्ट ऐन", "Law governing cheques and promissory notes", "Section 107 — cheque bounce"),
        ("RTI", "सूचना अधिकार", "Right to Information", "Request public body information"),
        ("public procurement", "सार्वजनिक खरिद", "Government tender process", "PPA compliance for bidders"),
        ("PPA", "सार्वजनिक खरिद ऐन", "Public Procurement Act", "Tender, bid security, evaluation"),
    ]
    return [legal_row(t, n, m, p) for t, n, m, p in terms]


def labor_row(term, nepali, meaning, calc):
    return {
        "term": term, "nepali": nepali, "meaning_en": meaning, "calculation_overview": calc,
        "common_questions": [f"{term} kati %?", f"{term} kasari calculate garne?"],
        "risk_level": "medium", "disclaimer_required": True, "disclaimer": LABOR_DISCLAIMER,
    }


def labor_ssf() -> list[dict]:
    terms = [
        ("salary", "तलब", "Employee remuneration", "Gross = basic + allowances — SSF on qualifying base"),
        ("basic salary", "मूल तलब", "Core salary before allowances", "Often base for SSF and gratuity"),
        ("allowance", "भत्ता", "Dearness, transport, housing etc.", "Some included in SSF base — verify"),
        ("dashain bonus", "दशैं भत्ता", "Festival bonus", "Often one month basic — Labour practice"),
        ("gratuity", "उपदान", "End-of-service benefit", "Half month per year of service — Gratuity Act"),
        ("SSF", "सामाजिक सुरक्षा कोष", "Social Security Fund", "Mandatory for formal sector employees"),
        ("employee contribution", "कर्मचारी योगदान", "Employee SSF share", "Typically 11% of qualifying salary — verify current"),
        ("employer contribution", "नियोक्ता योगदान", "Employer SSF share", "Typically 20% of qualifying salary — verify current"),
        ("PF", "भविष्य कोष", "Provident Fund — legacy parallel", "Being phased toward SSF unified system"),
        ("CIT", "नागरिक लगानी कोष", "Citizen Investment Trust", "Optional employee savings scheme"),
        ("overtime", "अतिरिक्त समय", "Work beyond standard hours", "Labour Act — premium rate applies"),
        ("leave encashment", "बिदा encashment", "Payment for unused leave", "Policy and Labour Act"),
        ("maternity leave", "प्रसूति बिदा", "Paid leave for childbirth", "Labour Act entitlement"),
        ("paternity leave", "पितृत्व बिदा", "Leave for new fathers", "As per Labour Act/rules"),
        ("sick leave", "विरामी बिदा", "Medical absence", "Annual entitlement per Labour Act"),
        ("casual leave", "प्रतिक्षा बिदा", "Short personal leave", "Annual quota"),
        ("home leave", "गृह बिदा", "Leave to visit home district", "For migrant workers — Labour Act"),
        ("Labour Act", "श्रम ऐन", "Primary employment law", "Wages, hours, termination, safety"),
        ("Labour Rules", "श्रम नियमावली", "Detailed labour regulations", "Implements Labour Act"),
        ("minimum wage", "न्यूनतम तलब", "Government floor wage", "Updated periodically — verify notice"),
        ("working hours", "कार्य समय", "Standard daily/weekly hours", "8 hours/day general rule"),
        ("weekly holiday", "साप्ताहिक विदा", "Mandatory rest day", "Usually Saturday in Nepal offices"),
        ("employment contract", "रोजगार सम्झौता", "Written terms of employment", "Position, wage, duration"),
        ("probation", "परिवीक्षा", "Trial period at start", "Shorter notice during probation"),
        ("severance", "विच्छेद भत्ता", "Payment on termination", "Based on service length — Labour Act"),
        ("union", "युनियन", "Workers' trade union", "Collective bargaining rights"),
        ("workplace safety", "कार्यस्थल सुरक्षा", "OHS obligations", "Employer duty under Labour Act"),
        ("child labour", "बाल श्रम", "Prohibited employment of minors", "Strict restrictions"),
        ("foreign employment", "वैदेशिक रोजगार", "Workers going abroad", "DOFE licensing for agencies"),
        ("payroll", "तलब प्रक्रिया", "Monthly salary processing", "Deductions: SSF, tax, advances"),
        ("PAYE", "तलबबाट कर कट्टी", "Income tax on salary", "Employer withholds monthly"),
        ("attendance", "हाजिरी", "Daily presence record", "Basis for payroll"),
        ("incentive", "प्रोत्साहन", "Performance bonus", "Taxable income"),
        ("deduction", "कटौती", "Salary reductions", "Advance recovery, absenteeism"),
        ("full and final", "अन्तिम मिलान", "Settlement on exit", "Gratuity, leave, dues clearance"),
        ("Form 16", "फारम १६", "Annual salary certificate", "For employee tax filing"),
        ("bonus tax", "बोनस कर", "Tax on bonus payment", "Treated as income"),
        ("contract worker", "ठेक्का कर्मचारी", "Workers on contract", "Different obligations — verify"),
        ("intern", "इन्टर्न", "Trainee position", "May be exempt from some SSF — verify"),
        ("EOBI equivalent", "सामाजिक सुरक्षा", "Social protection umbrella", "SSF consolidates prior schemes"),
    ]
    return [labor_row(t, n, m, c) for t, n, m, c in terms]


def acct_row(concept, nepali, meaning, simple, trick, confusions, examples):
    return {
        "concept": concept, "nepali": nepali, "meaning_en": meaning,
        "simple_explanation": simple, "memory_trick": trick,
        "common_confusions": confusions, "examples": examples,
    }


def accounting_concepts() -> list[dict]:
    return [
        acct_row("debit", "डेबिट / नामे", "Left side entry in double-entry bookkeeping",
                 "Paisa kahaa gayo / k aayo — asset ra kharcha badhcha",
                 "Debit = Door — asset/expense ma paisa aayo ki badhyo",
                 ["Debit does not always mean cash going out"],
                 ["Cash Dr 5000 — cash aayo", "Rent expense Dr 15000"]),
        acct_row("credit", "क्रेडिट / जम्मा", "Right side entry in double-entry",
                 "Paisa kaha bata aayo / kaha jancha — liability ra income badhcha",
                 "Credit = source — rin ra aamdani credit side",
                 ["Credit does not always mean money received"],
                 ["Sales Cr 10000", "Loan Cr 200000"]),
        acct_row("journal", "जर्नल", "Book of original entry for transactions",
                 "Har transaction ko pahilo record — date, narration, debit/credit",
                 "Journal = diary of business",
                 ["Journal vs ledger confusion"],
                 ["Daily sales journal entry", "Payment journal"]),
        acct_row("ledger", "खाता बही / लेजर", "Account-wise summary of all entries",
                 "Ek party/account ko sabai movement",
                 "Ledger = individual khata ko history",
                 ["Ledger is not trial balance"],
                 ["Ram ko ledger", "Cash ledger"]),
        acct_row("trial balance", "चाउकट बही", "List of all account balances — debit total = credit total",
                 "Month end check — mismatch bhayo bhane error cha",
                 "Trial = test before final reports",
                 ["Trial balance can balance with errors"],
                 ["TB mismatch → missing entry"]),
        acct_row("double entry", "दोहोरो लेखा", "Every transaction affects at least two accounts",
                 "Ek account debit, arko credit — total equal",
                 "Nothing comes from nowhere",
                 ["Single entry vs double entry"],
                 ["Cash sale: Cash Dr, Sales Cr"]),
        acct_row("balance sheet", "सम्पत्ति दायित्व विवरण", "Snapshot of assets, liabilities, equity at a date",
                 "Ke cha hamro sanga (asset) ra ke tirnu baki (liability)",
                 "Balance = what you own minus what you owe",
                 ["Not same as bank balance"],
                 ["sampatti = assets", "rin = liabilities"]),
        acct_row("profit and loss", "नाफा नोक्सान विवरण", "Income minus expenses for a period",
                 "Yo mahina kati kamayo kati kharcha bhayo",
                 "P&L = performance report",
                 ["Cash profit vs accounting profit"],
                 ["Sales - COGS - expenses = net profit"]),
        acct_row("cash flow", "नगद प्रवाह", "Actual cash in and out",
                 "Profit cha tara cash chaina — timing difference",
                 "Cash is king for small business",
                 ["Profit ≠ cash flow"],
                 ["Udharo bikri → profit but no cash"]),
        acct_row("asset", "सम्पत्ति", "Resource controlled with future economic benefit",
                 "Ghar, stock, cash, receivable — hamro ke cha",
                 "Asset = aafno",
                 ["Asset vs expense at purchase"],
                 ["Inventory asset", "Vehicle asset"]),
        acct_row("liability", "दायित्व / ऋण", "Present obligation to pay",
                 "Udharo, loan, payable — tirnu baki",
                 "Liability = arko ko paisa",
                 ["Liability vs expense"],
                 ["Supplier payable", "Bank loan"]),
        acct_row("equity", "पूँजी / इक्विटी", "Owner's residual interest",
                 "Malik le lagaako paisa + retained profit",
                 "Equity = net worth",
                 ["Equity vs liability"],
                 ["Capital introduced", "Retained earnings"]),
        acct_row("income", "आम्दानी", "Revenue from ordinary activities",
                 "Bikri, service fee — regular business kamai",
                 "Income = aaundai paisa",
                 ["Income vs gain"],
                 ["Sales income", "Service income"]),
        acct_row("expense", "खर्च", "Cost incurred to earn revenue",
                 "Talab, bhada, bijuli — business kharcha",
                 "Expense = jane paisa",
                 ["Expense vs asset purchase"],
                 ["Salary expense", "Rent expense"]),
        acct_row("gain", "लाभ", "Non-operating positive difference",
                 "Asset bechda book bhanda badhi ma",
                 "Gain = extra profit outside main business",
                 ["Gain vs income"],
                 ["Gain on asset sale"]),
        acct_row("loss", "नोक्सान", "Non-operating negative difference",
                 "Stock nash, asset impairment",
                 "Loss = business bata gako ghat",
                 ["Loss vs expense"],
                 ["noksan vo 400 — stock loss"]),
        acct_row("accrual", "उचित लेखा", "Record when earned/incurred not when cash moves",
                 "Mahina sakyo talab tirna baki — accrue garnu",
                 "Accrual = time match",
                 ["Cash basis vs accrual"],
                 ["Accrued salary", "Accrued rent"]),
        acct_row("matching", "मिलान सिद्धान्त", "Match expenses to related revenue period",
                 "J sales sanga jodiyeko kharcha tyahi period",
                 "Matching = fair picture",
                 ["Prepaid vs expense"],
                 ["COGS matched to sales"]),
        acct_row("going concern", "सतत सञ्चालन", "Assume business continues — not closing",
                 "Asset lai fire sale value ma lidaina",
                 "Going concern = business chalirahancha",
                 ["Liquidation basis different"],
                 ["Depreciation assumes going concern"]),
        acct_row("materiality", "महत्त्व", "Insignificant items can be simplified",
                 "Rs 50 typo — material chaina",
                 "Material = decision change garne",
                 ["Not excuse for fraud"],
                 ["Small stationery — immaterial"]),
        acct_row("depreciation", "मूल्यह्रास", "Systematic allocation of asset cost over life",
                 "Gadi, machine ko mulya hras",
                 "Depreciation = wear and tear in books",
                 ["Depreciation ≠ cash"],
                 ["depreciation 5000 monthly"]),
        acct_row("inventory", "स्टक / भण्डार", "Goods held for sale",
                 "Pasal ko saman — asset ho jaba samma becheko chaina",
                 "Inventory = becna baki mal",
                 ["Inventory vs COGS at sale"],
                 ["stock kineko", "stock valuation"]),
        acct_row("COGS", "बिक्री गरिएको वस्तुको लागत", "Cost of goods sold",
                 "Kinako saman ko cost jaba becheko",
                 "COGS = kinne cost of sold items",
                 ["COGS vs purchase"],
                 ["cogs 3000 for sales"]),
        acct_row("receivable", "लिन बाँकी", "Amount customers owe us",
                 "Udharo bikri — Ram bata lina baki",
                 "Receivable = aune paisa",
                 ["Receivable vs income"],
                 ["Ram lai 500 udhaar"]),
        acct_row("payable", "दिन बाँकी", "Amount we owe suppliers",
                 "Udharo kharid — supplier lai tirnu baki",
                 "Payable = tirnu baki",
                 ["Payable vs expense"],
                 ["Supplier payable 20000"]),
        acct_row("NAS", "नेपाल लेखा मानक", "Nepal Accounting Standards",
                 "Nepal ma company le follow garne standards",
                 "NAS = Nepal ko GAAP",
                 ["NAS vs IFRS"],
                 ["NAS for large entities"]),
        acct_row("NFRS", "नेपाल वित्तीय रिपोर्टिङ मानक", "Nepal Financial Reporting Standards",
                 "IFRS-aligned standards in Nepal",
                 "NFRS = updated framework",
                 ["NFRS for SMEs"],
                 ["Listed companies NFRS"]),
        acct_row("opening balance", "सुरुवाती मौज्दात", "Balances brought forward from prior period",
                 "Naya fiscal year suru ma agadi baki",
                 "Opening = last year closing",
                 ["Opening vs transaction"],
                 ["opening balance 50000 debtor"]),
        acct_row("closing balance", "अन्तिम मौज्दात", "Balance at period end",
                 "Month/year end pachi baki",
                 "Closing becomes next opening",
                 ["Closing vs trial balance"],
                 ["closing cash balance"]),
        acct_row("reconciliation", "मिलान", "Matching two records — bank vs books",
                 "Bank statement ra khata milaunu",
                 "Reconciliation = difference find",
                 ["Bank recon vs audit"],
                 ["bank reconciliation mismatch"]),
        acct_row("provision", "प्रावधान", "Estimated liability of uncertain timing",
                 "Bad debt huna sakcha — reserve rakhn",
                 "Provision = just in case",
                 ["Provision vs accrual"],
                 ["bad debt provision"]),
        acct_row("bad debt", "खराब देनदारी", "Uncollectible receivable",
                 "Ram le tirna sakdaina — write off",
                 "Bad debt = loss on credit sale",
                 ["Write-off vs provision"],
                 ["bad debt write off 2000"]),
        acct_row("working capital", "कारोबार पूँजी", "Current assets minus current liabilities",
                 "Daily operation chalauna paisa",
                 "Working capital = liquidity for business",
                 ["Not same as total capital"],
                 ["Low working capital risk"]),
        acct_row("capital introduced", "पूँजी थप", "Owner puts money into business",
                 "Malik le paisa haleko business ma",
                 "Capital intro = equity increase",
                 ["Not income"],
                 ["capital lagaayo 100000"]),
        acct_row("drawings", "निकासा", "Owner takes money out for personal use",
                 "Malik le personal lai paisa nikalyo",
                 "Drawings reduce equity",
                 ["Drawings vs salary"],
                 ["drawings 10000"]),
        acct_row("contra entry", "कन्ट्रा प्रविष्टि", "Transfer between related accounts",
                 "Cash bank ma haleko — cash ghatyo bank badhyo",
                 "Contra = internal move",
                 ["Not expense"],
                 ["cash to bank 20000"]),
        acct_row("narration", "विवरण", "Explanation text on voucher",
                 "Entry ko reason lekhne — 'bijuli bill'",
                 "Narration = future reference",
                 ["Missing narration causes confusion"],
                 ["narration: Ram le tiryo"]),
        acct_row("voucher", "भौचर", "Document supporting a journal entry",
                 "Proof — bill, receipt, memo",
                 "No voucher no entry — audit rule",
                 ["Voucher vs invoice"],
                 ["payment voucher", "journal voucher"]),
        acct_row("audit", "लेखा परीक्षण", "Independent examination of financial statements",
                 "CA le books check garne",
                 "Audit = trust certificate",
                 ["Audit vs tax inspection"],
                 ["statutory audit threshold"]),
    ]


def main() -> int:
    write_jsonl(REG / "tax_vocabulary.jsonl", tax_vocab())
    write_jsonl(REG / "legal_vocabulary.jsonl", legal_vocab())
    write_jsonl(REG / "labor_ssf.jsonl", labor_ssf())
    write_jsonl(KNOW / "accounting_concepts.jsonl", accounting_concepts())
    # banking, government, geography, festivals, food, construction, proverbs — part 2
    from bootstrap_nepal_ai_knowledge_part2 import write_part2
    write_part2(REG, KNOW, LANG, write_jsonl)
    print("Updated knowledge batches 21-26 + part2 (24-25, 35-39)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
