"""NIOS Capability Registry."""

from __future__ import annotations

from ..contracts.intelligence_contract import CapabilityDescriptor

BOOTSTRAP_CAPABILITIES: list[CapabilityDescriptor] = [
    CapabilityDescriptor(
        id="cap.chat.route",
        version="1.0.0",
        contract_version="1.0",
        tier="capability",
        inputs=[{"name": "message", "required": True}],
        outputs=[{"name": "intent"}],
        provides=["routing", "intent_classification"],
        requires=[],
        latency_p50_ms=5,
        cost_tier=0,
        confidence_floor=0.7,
        description="Intent routing",
    ),
    CapabilityDescriptor(
        id="cap.erp.ledger.balance",
        version="1.0.0",
        contract_version="1.0",
        tier="capability",
        inputs=[{"name": "party_name"}],
        outputs=[{"name": "balance"}],
        provides=["ledger_query", "balance"],
        requires=["cap.erp.session_snapshot"],
        latency_p50_ms=10,
        cost_tier=0,
        confidence_floor=1.0,
        description="Party balance from ERP snapshot",
    ),
    CapabilityDescriptor(
        id="cap.erp.session_snapshot",
        version="1.0.0",
        contract_version="1.0",
        tier="capability",
        inputs=[{"name": "session_id", "required": True}],
        outputs=[{"name": "snapshot"}],
        provides=["erp_data", "session_snapshot"],
        requires=[],
        latency_p50_ms=5,
        cost_tier=0,
        confidence_floor=1.0,
        description="ERP session snapshot",
    ),
    CapabilityDescriptor(
        id="cap.tax.vat.calculate",
        version="1.0.0",
        contract_version="1.0",
        tier="capability",
        inputs=[{"name": "invoice_lines", "required": True}],
        outputs=[{"name": "vat_amount"}],
        provides=["tax_calculation", "vat", "deterministic"],
        requires=[],
        latency_p50_ms=8,
        cost_tier=0,
        confidence_floor=1.0,
        description="VAT calculation",
    ),
    CapabilityDescriptor(
        id="cap.tax.tds.calculate",
        version="1.0.0",
        contract_version="1.0",
        tier="capability",
        inputs=[{"name": "taxable_amount", "required": True}],
        outputs=[{"name": "tds_amount"}],
        provides=["tax_calculation", "tds", "deterministic"],
        requires=[],
        latency_p50_ms=8,
        cost_tier=0,
        confidence_floor=1.0,
        description="TDS calculation",
    ),
    CapabilityDescriptor(
        id="cap.khata.entry.parse",
        version="1.0.0",
        contract_version="1.0",
        tier="capability",
        inputs=[{"name": "narration", "required": True}],
        outputs=[{"name": "journal_lines"}],
        provides=["khata_entry", "journal_parsing"],
        requires=[],
        latency_p50_ms=500,
        cost_tier=3,
        confidence_floor=0.8,
        description="Khata entry parsing",
    ),
    CapabilityDescriptor(
        id="cap.knowledge.nepal.search",
        version="1.0.0",
        contract_version="1.0",
        tier="capability",
        inputs=[{"name": "query", "required": True}],
        outputs=[{"name": "chunks"}],
        provides=["knowledge_retrieval", "nepal_tax"],
        requires=[],
        latency_p50_ms=50,
        cost_tier=1,
        confidence_floor=0.85,
        description="Nepal knowledge RAG",
    ),
    CapabilityDescriptor(
        id="cap.nav.erp.find",
        version="1.0.0",
        contract_version="1.0",
        tier="capability",
        inputs=[{"name": "query", "required": True}],
        outputs=[{"name": "page_id"}],
        provides=["navigation", "erp_howto"],
        requires=[],
        latency_p50_ms=20,
        cost_tier=1,
        confidence_floor=0.9,
        description="ERP navigation",
    ),
    CapabilityDescriptor(
        id="cap.language.detect",
        version="1.0.0",
        contract_version="1.0",
        tier="capability",
        inputs=[{"name": "text", "required": True}],
        outputs=[{"name": "language"}],
        provides=["language_detection"],
        requires=[],
        latency_p50_ms=3,
        cost_tier=0,
        confidence_floor=0.95,
        description="Language detection",
    ),
    CapabilityDescriptor(
        id="cap.cache.semantic",
        version="1.0.0",
        contract_version="1.0",
        tier="capability",
        inputs=[{"name": "query", "required": True}],
        outputs=[{"name": "cached_answer"}],
        provides=["semantic_cache"],
        requires=[],
        latency_p50_ms=5,
        cost_tier=0,
        confidence_floor=0.95,
        description="Semantic cache",
    ),
    CapabilityDescriptor(
        id="cap.engine.payroll",
        version="1.0.0",
        contract_version="1.0",
        tier="capability",
        inputs=[{"name": "basic_salary", "required": True}],
        outputs=[{"name": "net_pay"}, {"name": "tds_monthly"}],
        provides=["payroll", "deterministic", "simulation"],
        requires=[],
        latency_p50_ms=5,
        cost_tier=0,
        confidence_floor=1.0,
        description="Nepal payroll engine",
    ),
    CapabilityDescriptor(
        id="cap.engine.simulation",
        version="1.0.0",
        contract_version="1.0",
        tier="capability",
        inputs=[{"name": "scenario", "required": True}],
        outputs=[{"name": "deltas"}, {"name": "impacts"}],
        provides=["simulation", "what_if", "deterministic"],
        requires=["cap.engine.payroll"],
        latency_p50_ms=15,
        cost_tier=0,
        confidence_floor=1.0,
        description="Universal simulation engine",
    ),
    CapabilityDescriptor(
        id="cap.engine.accounting",
        version="1.0.0",
        contract_version="1.0",
        tier="capability",
        inputs=[{"name": "ledger_snapshot"}],
        outputs=[{"name": "ratios"}],
        provides=["accounting", "deterministic"],
        requires=["cap.erp.session_snapshot"],
        latency_p50_ms=10,
        cost_tier=0,
        confidence_floor=1.0,
        description="Accounting ratios engine",
    ),
    CapabilityDescriptor(
        id="cap.engine.journal",
        version="1.0.0",
        contract_version="1.0",
        tier="capability",
        inputs=[{"name": "journal_lines", "required": True}],
        outputs=[{"name": "balanced"}],
        provides=["journal", "deterministic"],
        requires=[],
        latency_p50_ms=5,
        cost_tier=0,
        confidence_floor=1.0,
        description="Journal validation engine",
    ),
    CapabilityDescriptor(
        id="cap.engine.depreciation",
        version="1.0.0",
        contract_version="1.0",
        tier="capability",
        inputs=[{"name": "asset_value", "required": True}],
        outputs=[{"name": "depreciation"}],
        provides=["depreciation", "deterministic"],
        requires=[],
        latency_p50_ms=8,
        cost_tier=0,
        confidence_floor=1.0,
        description="Depreciation engine",
    ),
    CapabilityDescriptor(
        id="cap.world_state.query",
        version="1.0.0",
        contract_version="1.0",
        tier="capability",
        inputs=[{"name": "intent", "required": True}],
        outputs=[{"name": "slices"}, {"name": "summary"}],
        provides=["world_state", "digital_twin"],
        requires=[],
        latency_p50_ms=10,
        cost_tier=0,
        confidence_floor=1.0,
        description="World State Engine — 12 domains",
    ),
    CapabilityDescriptor(
        id="cap.knowledge.graph",
        version="1.0.0",
        contract_version="1.0",
        tier="capability",
        inputs=[{"name": "query"}],
        outputs=[{"name": "nodes"}, {"name": "edges"}],
        provides=["knowledge_graph", "temporal"],
        requires=[],
        latency_p50_ms=20,
        cost_tier=1,
        confidence_floor=0.9,
        description="Temporal knowledge graph",
    ),
    CapabilityDescriptor(
        id="cap.ontology.query",
        version="1.0.0",
        contract_version="1.0",
        tier="capability",
        inputs=[{"name": "concept", "required": True}],
        outputs=[{"name": "rules"}, {"name": "relations"}],
        provides=["ontology", "temporal_rules"],
        requires=["cap.knowledge.graph"],
        latency_p50_ms=15,
        cost_tier=1,
        confidence_floor=0.95,
        description="Universal ontology with temporal rule selection",
    ),
    CapabilityDescriptor(
        id="cap.digital_twin.build",
        version="1.0.0",
        contract_version="1.0",
        tier="capability",
        inputs=[{"name": "company_id"}],
        outputs=[{"name": "twin"}, {"name": "health_score"}],
        provides=["digital_twin", "business_health"],
        requires=["cap.world_state.query"],
        latency_p50_ms=12,
        cost_tier=0,
        confidence_floor=1.0,
        description="Per-business digital twin",
    ),
    CapabilityDescriptor(
        id="cap.prediction.forecast",
        version="1.0.0",
        contract_version="1.0",
        tier="capability",
        inputs=[{"name": "metric", "required": True}],
        outputs=[{"name": "forecast"}],
        provides=["prediction", "cashflow", "tax_liability"],
        requires=["cap.world_state.query"],
        latency_p50_ms=25,
        cost_tier=1,
        confidence_floor=0.85,
        description="Cashflow and tax liability forecasts",
    ),
    CapabilityDescriptor(
        id="cap.federation.query",
        version="1.0.0",
        contract_version="1.0",
        tier="capability",
        inputs=[{"name": "intent", "required": True}, {"name": "query", "required": True}],
        outputs=[{"name": "evidence"}],
        provides=["federation", "knowledge_retrieval"],
        requires=[],
        latency_p50_ms=30,
        cost_tier=2,
        confidence_floor=0.85,
        description="Federated knowledge query",
    ),
    CapabilityDescriptor(
        id="cap.autonomous.task",
        version="1.0.0",
        contract_version="1.0",
        tier="capability",
        inputs=[{"name": "context"}],
        outputs=[{"name": "tasks"}],
        provides=["autonomous", "monitoring", "compliance"],
        requires=["cap.world_state.query"],
        latency_p50_ms=10,
        cost_tier=1,
        confidence_floor=0.9,
        description="Autonomous task engine",
    ),
    CapabilityDescriptor(
        id="cap.governance.audit",
        version="1.0.0",
        contract_version="1.0",
        tier="capability",
        inputs=[{"name": "action", "required": True}],
        outputs=[{"name": "audit_id"}],
        provides=["governance", "audit"],
        requires=[],
        latency_p50_ms=5,
        cost_tier=0,
        confidence_floor=1.0,
        description="Governance audit trail",
    ),
    CapabilityDescriptor(
        id="cap.governance.approval",
        version="1.0.0",
        contract_version="1.0",
        tier="capability",
        inputs=[{"name": "action_type", "required": True}],
        outputs=[{"name": "allowed"}, {"name": "approval_id"}],
        provides=["governance", "approval"],
        requires=["cap.governance.audit"],
        latency_p50_ms=8,
        cost_tier=0,
        confidence_floor=1.0,
        description="Human-in-the-loop approvals",
    ),
    CapabilityDescriptor(
        id="cap.ocr.invoice",
        version="1.0.0",
        contract_version="1.0",
        tier="capability",
        inputs=[{"name": "text_or_image", "required": True}],
        outputs=[{"name": "draft_invoice"}],
        provides=["ocr", "invoice_draft"],
        requires=["cap.governance.audit"],
        latency_p50_ms=200,
        cost_tier=2,
        confidence_floor=0.75,
        description="OCR to draft invoice via UIL",
    ),
    CapabilityDescriptor(
        id="cap.evolution.reasoner",
        version="1.0.0",
        contract_version="1.0",
        tier="capability",
        inputs=[{"name": "prompt", "required": True}],
        outputs=[{"name": "response"}],
        provides=["reasoning", "model_agnostic"],
        requires=[],
        latency_p50_ms=500,
        cost_tier=3,
        confidence_floor=0.7,
        description="Evolution layer reasoner adapter",
    ),
    CapabilityDescriptor(
        id="cap.benchmark.nightly",
        version="1.0.0",
        contract_version="1.0",
        tier="capability",
        inputs=[],
        outputs=[{"name": "report"}],
        provides=["benchmark", "regression"],
        requires=[],
        latency_p50_ms=1000,
        cost_tier=1,
        confidence_floor=1.0,
        description="Nightly benchmark suites",
    ),
]


class CapabilityRegistry:
    def __init__(self) -> None:
        self._caps: dict[str, CapabilityDescriptor] = {
            c.id: c for c in BOOTSTRAP_CAPABILITIES
        }

    def get(self, cap_id: str) -> CapabilityDescriptor | None:
        return self._caps.get(cap_id)

    def list_all(self) -> list[CapabilityDescriptor]:
        return list(self._caps.values())

    def find_by_provides(self, tag: str) -> list[CapabilityDescriptor]:
        return [c for c in self._caps.values() if tag in c.provides]

    def register(self, descriptor: CapabilityDescriptor) -> None:
        self._caps[descriptor.id] = descriptor


registry = CapabilityRegistry()
