"""MAI-03 stage catalogue — emit only stages that actually execute."""

from __future__ import annotations

from enum import Enum


class TraceStage(str, Enum):
    GATEWAY_RECEIVED = "GATEWAY_RECEIVED"
    AUTHENTICATION_RESOLVED = "AUTHENTICATION_RESOLVED"
    TENANT_SCOPE_VALIDATED = "TENANT_SCOPE_VALIDATED"
    CONSTITUTION_POLICY_EVALUATED = "CONSTITUTION_POLICY_EVALUATED"
    CLIENT_CONTRACT_VALIDATED = "CLIENT_CONTRACT_VALIDATED"
    CANONICAL_REQUEST_BUILT = "CANONICAL_REQUEST_BUILT"
    ORCHESTRATOR_STARTED = "ORCHESTRATOR_STARTED"
    DETERMINISTIC_PREPROCESS_STARTED = "DETERMINISTIC_PREPROCESS_STARTED"
    DETERMINISTIC_PREPROCESS_COMPLETED = "DETERMINISTIC_PREPROCESS_COMPLETED"
    CONTEXT_LOAD_STARTED = "CONTEXT_LOAD_STARTED"
    CONTEXT_LOAD_COMPLETED = "CONTEXT_LOAD_COMPLETED"
    LANGUAGE_ANALYSIS_STARTED = "LANGUAGE_ANALYSIS_STARTED"
    LANGUAGE_ANALYSIS_COMPLETED = "LANGUAGE_ANALYSIS_COMPLETED"
    NORMALIZATION_STARTED = "NORMALIZATION_STARTED"
    NORMALIZATION_COMPLETED = "NORMALIZATION_COMPLETED"
    TRANSLITERATION_STARTED = "TRANSLITERATION_STARTED"
    TRANSLITERATION_COMPLETED = "TRANSLITERATION_COMPLETED"
    TRANSLITERATION_SKIPPED = "TRANSLITERATION_SKIPPED"
    TRANSLITERATION_FAILED = "TRANSLITERATION_FAILED"
    TYPO_CODE_MIX_STARTED = "TYPO_CODE_MIX_STARTED"
    TYPO_CODE_MIX_COMPLETED = "TYPO_CODE_MIX_COMPLETED"
    TYPO_CODE_MIX_FAILED = "TYPO_CODE_MIX_FAILED"
    NUMBER_ROLES_STARTED = "NUMBER_ROLES_STARTED"
    NUMBER_ROLES_COMPLETED = "NUMBER_ROLES_COMPLETED"
    NUMBER_ROLES_FAILED = "NUMBER_ROLES_FAILED"
    DOMAIN_LEXICON_STARTED = "DOMAIN_LEXICON_STARTED"
    DOMAIN_LEXICON_COMPLETED = "DOMAIN_LEXICON_COMPLETED"
    DOMAIN_LEXICON_FAILED = "DOMAIN_LEXICON_FAILED"
    RESPONSE_REGISTER_STARTED = "RESPONSE_REGISTER_STARTED"
    RESPONSE_REGISTER_COMPLETED = "RESPONSE_REGISTER_COMPLETED"
    RESPONSE_REGISTER_FAILED = "RESPONSE_REGISTER_FAILED"
    OBJECT_REFERENCE_STARTED = "OBJECT_REFERENCE_STARTED"
    OBJECT_REFERENCE_COMPLETED = "OBJECT_REFERENCE_COMPLETED"
    OBJECT_REFERENCE_FAILED = "OBJECT_REFERENCE_FAILED"
    TURN_RELATION_STARTED = "TURN_RELATION_STARTED"
    TURN_RELATION_COMPLETED = "TURN_RELATION_COMPLETED"
    TURN_RELATION_FAILED = "TURN_RELATION_FAILED"
    REFERENCE_COREFERENCE_STARTED = "REFERENCE_COREFERENCE_STARTED"
    REFERENCE_COREFERENCE_COMPLETED = "REFERENCE_COREFERENCE_COMPLETED"
    REFERENCE_COREFERENCE_FAILED = "REFERENCE_COREFERENCE_FAILED"
    CONTEXT_ASSEMBLY_STARTED = "CONTEXT_ASSEMBLY_STARTED"
    CONTEXT_ASSEMBLY_COMPLETED = "CONTEXT_ASSEMBLY_COMPLETED"
    CONTEXT_ASSEMBLY_FAILED = "CONTEXT_ASSEMBLY_FAILED"
    ROUTING_STARTED = "ROUTING_STARTED"
    ROUTING_COMPLETED = "ROUTING_COMPLETED"
    ROUTING_FAILED = "ROUTING_FAILED"
    EVENT_SPEC_REGISTRY_STARTED = "EVENT_SPEC_REGISTRY_STARTED"
    EVENT_SPEC_REGISTRY_COMPLETED = "EVENT_SPEC_REGISTRY_COMPLETED"
    EVENT_SPEC_REGISTRY_FAILED = "EVENT_SPEC_REGISTRY_FAILED"
    EVENT_FRAME_EXTRACTION_STARTED = "EVENT_FRAME_EXTRACTION_STARTED"
    EVENT_FRAME_EXTRACTION_COMPLETED = "EVENT_FRAME_EXTRACTION_COMPLETED"
    EVENT_FRAME_EXTRACTION_FAILED = "EVENT_FRAME_EXTRACTION_FAILED"
    CLARIFICATION_PLAN_STARTED = "CLARIFICATION_PLAN_STARTED"
    CLARIFICATION_PLAN_COMPLETED = "CLARIFICATION_PLAN_COMPLETED"
    CLARIFICATION_PLAN_FAILED = "CLARIFICATION_PLAN_FAILED"
    TYPED_PLAN_STARTED = "TYPED_PLAN_STARTED"
    TYPED_PLAN_COMPLETED = "TYPED_PLAN_COMPLETED"
    TYPED_PLAN_FAILED = "TYPED_PLAN_FAILED"
    PROVIDER_CASCADE_STARTED = "PROVIDER_CASCADE_STARTED"
    PROVIDER_CASCADE_COMPLETED = "PROVIDER_CASCADE_COMPLETED"
    PROVIDER_CASCADE_FAILED = "PROVIDER_CASCADE_FAILED"
    PROMPT_REGISTRY_STARTED = "PROMPT_REGISTRY_STARTED"
    PROMPT_REGISTRY_COMPLETED = "PROMPT_REGISTRY_COMPLETED"
    PROMPT_REGISTRY_FAILED = "PROMPT_REGISTRY_FAILED"
    KNOWLEDGE_SOURCE_GOVERNANCE_STARTED = "KNOWLEDGE_SOURCE_GOVERNANCE_STARTED"
    KNOWLEDGE_SOURCE_GOVERNANCE_COMPLETED = "KNOWLEDGE_SOURCE_GOVERNANCE_COMPLETED"
    KNOWLEDGE_SOURCE_GOVERNANCE_FAILED = "KNOWLEDGE_SOURCE_GOVERNANCE_FAILED"
    STRUCTURAL_SEGMENTATION_STARTED = "STRUCTURAL_SEGMENTATION_STARTED"
    STRUCTURAL_SEGMENTATION_COMPLETED = "STRUCTURAL_SEGMENTATION_COMPLETED"
    STRUCTURAL_SEGMENTATION_FAILED = "STRUCTURAL_SEGMENTATION_FAILED"
    EXTRACTION_OCR_PLAN_STARTED = "EXTRACTION_OCR_PLAN_STARTED"
    EXTRACTION_OCR_PLAN_COMPLETED = "EXTRACTION_OCR_PLAN_COMPLETED"
    EXTRACTION_OCR_PLAN_FAILED = "EXTRACTION_OCR_PLAN_FAILED"
    TEMPORAL_CROSS_REF_STARTED = "TEMPORAL_CROSS_REF_STARTED"
    TEMPORAL_CROSS_REF_COMPLETED = "TEMPORAL_CROSS_REF_COMPLETED"
    TEMPORAL_CROSS_REF_FAILED = "TEMPORAL_CROSS_REF_FAILED"
    LEXICAL_INDEX_STARTED = "LEXICAL_INDEX_STARTED"
    LEXICAL_INDEX_COMPLETED = "LEXICAL_INDEX_COMPLETED"
    LEXICAL_INDEX_FAILED = "LEXICAL_INDEX_FAILED"
    VECTOR_INDEX_STARTED = "VECTOR_INDEX_STARTED"
    VECTOR_INDEX_COMPLETED = "VECTOR_INDEX_COMPLETED"
    VECTOR_INDEX_FAILED = "VECTOR_INDEX_FAILED"
    HYBRID_FUSION_STARTED = "HYBRID_FUSION_STARTED"
    HYBRID_FUSION_COMPLETED = "HYBRID_FUSION_COMPLETED"
    HYBRID_FUSION_FAILED = "HYBRID_FUSION_FAILED"
    CLAIM_CITATION_STARTED = "CLAIM_CITATION_STARTED"
    CLAIM_CITATION_COMPLETED = "CLAIM_CITATION_COMPLETED"
    CLAIM_CITATION_FAILED = "CLAIM_CITATION_FAILED"
    DOMAIN_PORT_MAPPING_STARTED = "DOMAIN_PORT_MAPPING_STARTED"
    DOMAIN_PORT_MAPPING_COMPLETED = "DOMAIN_PORT_MAPPING_COMPLETED"
    DOMAIN_PORT_MAPPING_FAILED = "DOMAIN_PORT_MAPPING_FAILED"
    DURABLE_VERSIONED_DRAFT_STARTED = "DURABLE_VERSIONED_DRAFT_STARTED"
    DURABLE_VERSIONED_DRAFT_COMPLETED = "DURABLE_VERSIONED_DRAFT_COMPLETED"
    DURABLE_VERSIONED_DRAFT_FAILED = "DURABLE_VERSIONED_DRAFT_FAILED"
    DETERMINISTIC_PREVIEW_EDIT_LOOP_STARTED = (
        "DETERMINISTIC_PREVIEW_EDIT_LOOP_STARTED"
    )
    DETERMINISTIC_PREVIEW_EDIT_LOOP_COMPLETED = (
        "DETERMINISTIC_PREVIEW_EDIT_LOOP_COMPLETED"
    )
    DETERMINISTIC_PREVIEW_EDIT_LOOP_FAILED = (
        "DETERMINISTIC_PREVIEW_EDIT_LOOP_FAILED"
    )
    EXPLICIT_CONFIRMATION_OEC_DISPATCH_STARTED = (
        "EXPLICIT_CONFIRMATION_OEC_DISPATCH_STARTED"
    )
    EXPLICIT_CONFIRMATION_OEC_DISPATCH_COMPLETED = (
        "EXPLICIT_CONFIRMATION_OEC_DISPATCH_COMPLETED"
    )
    EXPLICIT_CONFIRMATION_OEC_DISPATCH_FAILED = (
        "EXPLICIT_CONFIRMATION_OEC_DISPATCH_FAILED"
    )
    OFFLINE_SYNC_CONFLICT_REVERSAL_STARTED = (
        "OFFLINE_SYNC_CONFLICT_REVERSAL_STARTED"
    )
    OFFLINE_SYNC_CONFLICT_REVERSAL_COMPLETED = (
        "OFFLINE_SYNC_CONFLICT_REVERSAL_COMPLETED"
    )
    OFFLINE_SYNC_CONFLICT_REVERSAL_FAILED = (
        "OFFLINE_SYNC_CONFLICT_REVERSAL_FAILED"
    )
    LEGAL_QUESTION_RESEARCH_STARTED = "LEGAL_QUESTION_RESEARCH_STARTED"
    LEGAL_QUESTION_RESEARCH_COMPLETED = "LEGAL_QUESTION_RESEARCH_COMPLETED"
    LEGAL_QUESTION_RESEARCH_FAILED = "LEGAL_QUESTION_RESEARCH_FAILED"
    CORE_NEPAL_TAX_KNOWLEDGE_PILOT_STARTED = (
        "CORE_NEPAL_TAX_KNOWLEDGE_PILOT_STARTED"
    )
    CORE_NEPAL_TAX_KNOWLEDGE_PILOT_COMPLETED = (
        "CORE_NEPAL_TAX_KNOWLEDGE_PILOT_COMPLETED"
    )
    CORE_NEPAL_TAX_KNOWLEDGE_PILOT_FAILED = (
        "CORE_NEPAL_TAX_KNOWLEDGE_PILOT_FAILED"
    )
    TAX_CALCULATOR_RULE_INTEGRATION_STARTED = (
        "TAX_CALCULATOR_RULE_INTEGRATION_STARTED"
    )
    TAX_CALCULATOR_RULE_INTEGRATION_COMPLETED = (
        "TAX_CALCULATOR_RULE_INTEGRATION_COMPLETED"
    )
    TAX_CALCULATOR_RULE_INTEGRATION_FAILED = (
        "TAX_CALCULATOR_RULE_INTEGRATION_FAILED"
    )
    NFRS_NAS_POLICY_DISCLOSURE_PILOT_STARTED = (
        "NFRS_NAS_POLICY_DISCLOSURE_PILOT_STARTED"
    )
    NFRS_NAS_POLICY_DISCLOSURE_PILOT_COMPLETED = (
        "NFRS_NAS_POLICY_DISCLOSURE_PILOT_COMPLETED"
    )
    NFRS_NAS_POLICY_DISCLOSURE_PILOT_FAILED = (
        "NFRS_NAS_POLICY_DISCLOSURE_PILOT_FAILED"
    )
    FINANCIAL_CLOSE_ADJUSTMENT_ASSISTANCE_STARTED = (
        "FINANCIAL_CLOSE_ADJUSTMENT_ASSISTANCE_STARTED"
    )
    FINANCIAL_CLOSE_ADJUSTMENT_ASSISTANCE_COMPLETED = (
        "FINANCIAL_CLOSE_ADJUSTMENT_ASSISTANCE_COMPLETED"
    )
    FINANCIAL_CLOSE_ADJUSTMENT_ASSISTANCE_FAILED = (
        "FINANCIAL_CLOSE_ADJUSTMENT_ASSISTANCE_FAILED"
    )
    BROADER_NEPAL_BUSINESS_LAW_DOMAIN_RELEASE_STARTED = (
        "BROADER_NEPAL_BUSINESS_LAW_DOMAIN_RELEASE_STARTED"
    )
    BROADER_NEPAL_BUSINESS_LAW_DOMAIN_RELEASE_COMPLETED = (
        "BROADER_NEPAL_BUSINESS_LAW_DOMAIN_RELEASE_COMPLETED"
    )
    BROADER_NEPAL_BUSINESS_LAW_DOMAIN_RELEASE_FAILED = (
        "BROADER_NEPAL_BUSINESS_LAW_DOMAIN_RELEASE_FAILED"
    )
    JUDICIAL_DECISION_INTELLIGENCE_STARTED = (
        "JUDICIAL_DECISION_INTELLIGENCE_STARTED"
    )
    JUDICIAL_DECISION_INTELLIGENCE_COMPLETED = (
        "JUDICIAL_DECISION_INTELLIGENCE_COMPLETED"
    )
    JUDICIAL_DECISION_INTELLIGENCE_FAILED = (
        "JUDICIAL_DECISION_INTELLIGENCE_FAILED"
    )
    CONTINUOUS_CHANGE_INTELLIGENCE_STARTED = (
        "CONTINUOUS_CHANGE_INTELLIGENCE_STARTED"
    )
    CONTINUOUS_CHANGE_INTELLIGENCE_COMPLETED = (
        "CONTINUOUS_CHANGE_INTELLIGENCE_COMPLETED"
    )
    CONTINUOUS_CHANGE_INTELLIGENCE_FAILED = (
        "CONTINUOUS_CHANGE_INTELLIGENCE_FAILED"
    )
    SECURITY_TENANT_RED_TEAM_STARTED = "SECURITY_TENANT_RED_TEAM_STARTED"
    SECURITY_TENANT_RED_TEAM_COMPLETED = "SECURITY_TENANT_RED_TEAM_COMPLETED"
    SECURITY_TENANT_RED_TEAM_FAILED = "SECURITY_TENANT_RED_TEAM_FAILED"
    LOAD_LATENCY_FAILOVER_STARTED = "LOAD_LATENCY_FAILOVER_STARTED"
    LOAD_LATENCY_FAILOVER_COMPLETED = "LOAD_LATENCY_FAILOVER_COMPLETED"
    LOAD_LATENCY_FAILOVER_FAILED = "LOAD_LATENCY_FAILOVER_FAILED"
    BACKUP_RESTORE_DISASTER_LIFECYCLE_STARTED = (
        "BACKUP_RESTORE_DISASTER_LIFECYCLE_STARTED"
    )
    BACKUP_RESTORE_DISASTER_LIFECYCLE_COMPLETED = (
        "BACKUP_RESTORE_DISASTER_LIFECYCLE_COMPLETED"
    )
    BACKUP_RESTORE_DISASTER_LIFECYCLE_FAILED = (
        "BACKUP_RESTORE_DISASTER_LIFECYCLE_FAILED"
    )
    HUMAN_REVIEW_PILOT_OPERATIONS_STARTED = (
        "HUMAN_REVIEW_PILOT_OPERATIONS_STARTED"
    )
    HUMAN_REVIEW_PILOT_OPERATIONS_COMPLETED = (
        "HUMAN_REVIEW_PILOT_OPERATIONS_COMPLETED"
    )
    HUMAN_REVIEW_PILOT_OPERATIONS_FAILED = (
        "HUMAN_REVIEW_PILOT_OPERATIONS_FAILED"
    )
    GOVERNED_IMPROVEMENT_FINE_TUNING_STARTED = (
        "GOVERNED_IMPROVEMENT_FINE_TUNING_STARTED"
    )
    GOVERNED_IMPROVEMENT_FINE_TUNING_COMPLETED = (
        "GOVERNED_IMPROVEMENT_FINE_TUNING_COMPLETED"
    )
    GOVERNED_IMPROVEMENT_FINE_TUNING_FAILED = (
        "GOVERNED_IMPROVEMENT_FINE_TUNING_FAILED"
    )
    PRODUCTION_CAPABILITY_RELEASE_STARTED = (
        "PRODUCTION_CAPABILITY_RELEASE_STARTED"
    )
    PRODUCTION_CAPABILITY_RELEASE_COMPLETED = (
        "PRODUCTION_CAPABILITY_RELEASE_COMPLETED"
    )
    PRODUCTION_CAPABILITY_RELEASE_FAILED = (
        "PRODUCTION_CAPABILITY_RELEASE_FAILED"
    )
    NEPALI_ENGLISH_SPEECH_CHANNEL_STARTED = (
        "NEPALI_ENGLISH_SPEECH_CHANNEL_STARTED"
    )
    NEPALI_ENGLISH_SPEECH_CHANNEL_COMPLETED = (
        "NEPALI_ENGLISH_SPEECH_CHANNEL_COMPLETED"
    )
    NEPALI_ENGLISH_SPEECH_CHANNEL_FAILED = (
        "NEPALI_ENGLISH_SPEECH_CHANNEL_FAILED"
    )
    PRIVATE_USER_DOCUMENT_INTELLIGENCE_STARTED = (
        "PRIVATE_USER_DOCUMENT_INTELLIGENCE_STARTED"
    )
    PRIVATE_USER_DOCUMENT_INTELLIGENCE_COMPLETED = (
        "PRIVATE_USER_DOCUMENT_INTELLIGENCE_COMPLETED"
    )
    PRIVATE_USER_DOCUMENT_INTELLIGENCE_FAILED = (
        "PRIVATE_USER_DOCUMENT_INTELLIGENCE_FAILED"
    )
    CA_FIRM_ENGAGEMENT_WORKPAPER_STARTED = (
        "CA_FIRM_ENGAGEMENT_WORKPAPER_STARTED"
    )
    CA_FIRM_ENGAGEMENT_WORKPAPER_COMPLETED = (
        "CA_FIRM_ENGAGEMENT_WORKPAPER_COMPLETED"
    )
    CA_FIRM_ENGAGEMENT_WORKPAPER_FAILED = (
        "CA_FIRM_ENGAGEMENT_WORKPAPER_FAILED"
    )
    COMPLIANCE_OBLIGATION_CALENDAR_STARTED = (
        "COMPLIANCE_OBLIGATION_CALENDAR_STARTED"
    )
    COMPLIANCE_OBLIGATION_CALENDAR_COMPLETED = (
        "COMPLIANCE_OBLIGATION_CALENDAR_COMPLETED"
    )
    COMPLIANCE_OBLIGATION_CALENDAR_FAILED = (
        "COMPLIANCE_OBLIGATION_CALENDAR_FAILED"
    )
    PLANNING_STARTED = "PLANNING_STARTED"
    PLANNING_COMPLETED = "PLANNING_COMPLETED"
    MODEL_REQUEST_STARTED = "MODEL_REQUEST_STARTED"
    MODEL_REQUEST_COMPLETED = "MODEL_REQUEST_COMPLETED"
    TOOL_CALL_STARTED = "TOOL_CALL_STARTED"
    TOOL_CALL_COMPLETED = "TOOL_CALL_COMPLETED"
    KNOWLEDGE_RETRIEVAL_STARTED = "KNOWLEDGE_RETRIEVAL_STARTED"
    KNOWLEDGE_RETRIEVAL_COMPLETED = "KNOWLEDGE_RETRIEVAL_COMPLETED"
    EVIDENCE_ASSEMBLY_COMPLETED = "EVIDENCE_ASSEMBLY_COMPLETED"
    RESPONSE_VALIDATION_STARTED = "RESPONSE_VALIDATION_STARTED"
    RESPONSE_VALIDATION_COMPLETED = "RESPONSE_VALIDATION_COMPLETED"
    SSE_STREAM_STARTED = "SSE_STREAM_STARTED"
    SSE_STREAM_COMPLETED = "SSE_STREAM_COMPLETED"
    DRAFT_TRANSITION = "DRAFT_TRANSITION"
    PREVIEW_GENERATED = "PREVIEW_GENERATED"
    CONFIRMATION_EVALUATED = "CONFIRMATION_EVALUATED"
    ACTION_DISPATCH_STARTED = "ACTION_DISPATCH_STARTED"
    ACTION_DISPATCH_COMPLETED = "ACTION_DISPATCH_COMPLETED"
    SYNC_STARTED = "SYNC_STARTED"
    SYNC_COMPLETED = "SYNC_COMPLETED"
    REQUEST_COMPLETED = "REQUEST_COMPLETED"
    REQUEST_FAILED = "REQUEST_FAILED"
    REQUEST_CANCELLED = "REQUEST_CANCELLED"


class TraceStatus(str, Enum):
    STARTED = "STARTED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    BLOCKED = "BLOCKED"
    DEGRADED = "DEGRADED"


# Stages that are active for Orbix ingress path today (others registered for later MAI).
ACTIVE_ORBIT_STAGES: frozenset[TraceStage] = frozenset(
    {
        TraceStage.GATEWAY_RECEIVED,
        TraceStage.AUTHENTICATION_RESOLVED,
        TraceStage.TENANT_SCOPE_VALIDATED,
        TraceStage.CONSTITUTION_POLICY_EVALUATED,
        TraceStage.CLIENT_CONTRACT_VALIDATED,
        TraceStage.CANONICAL_REQUEST_BUILT,
        TraceStage.ORCHESTRATOR_STARTED,
        TraceStage.DETERMINISTIC_PREPROCESS_STARTED,
        TraceStage.DETERMINISTIC_PREPROCESS_COMPLETED,
        TraceStage.MODEL_REQUEST_STARTED,
        TraceStage.MODEL_REQUEST_COMPLETED,
        TraceStage.RESPONSE_VALIDATION_STARTED,
        TraceStage.RESPONSE_VALIDATION_COMPLETED,
        TraceStage.SSE_STREAM_STARTED,
        TraceStage.SSE_STREAM_COMPLETED,
        TraceStage.CONFIRMATION_EVALUATED,
        TraceStage.REQUEST_COMPLETED,
        TraceStage.REQUEST_FAILED,
        TraceStage.REQUEST_CANCELLED,
    }
)


TERMINAL_STAGES: frozenset[TraceStage] = frozenset(
    {
        TraceStage.REQUEST_COMPLETED,
        TraceStage.REQUEST_FAILED,
        TraceStage.REQUEST_CANCELLED,
    }
)


def assert_known_stage(stage: str | TraceStage) -> TraceStage:
    if isinstance(stage, TraceStage):
        return stage
    try:
        return TraceStage(stage)
    except ValueError as exc:
        raise ValueError(f"UNKNOWN_TRACE_STAGE:{stage}") from exc
