"""MAI-03 stage catalogue — emit only stages that actually execute."""

from __future__ import annotations

from enum import Enum


class TraceStage(str, Enum):
    GATEWAY_RECEIVED = "GATEWAY_RECEIVED"
    AUTHENTICATION_RESOLVED = "AUTHENTICATION_RESOLVED"
    TENANT_SCOPE_VALIDATED = "TENANT_SCOPE_VALIDATED"
    CONSTITUTION_POLICY_EVALUATED = "CONSTITUTION_POLICY_EVALUATED"
    CLIENT_CONTRACT_VALIDATED = "CLIENT_CONTRACT_VALIDATED"
    CANONICAL_REQUEST_BUILT = "CANONICAL_REQUEST_BUILT"
    ORCHESTRATOR_STARTED = "ORCHESTRATOR_STARTED"
    DETERMINISTIC_PREPROCESS_STARTED = "DETERMINISTIC_PREPROCESS_STARTED"
    DETERMINISTIC_PREPROCESS_COMPLETED = "DETERMINISTIC_PREPROCESS_COMPLETED"
    CONTEXT_LOAD_STARTED = "CONTEXT_LOAD_STARTED"
    CONTEXT_LOAD_COMPLETED = "CONTEXT_LOAD_COMPLETED"
    LANGUAGE_ANALYSIS_STARTED = "LANGUAGE_ANALYSIS_STARTED"
    LANGUAGE_ANALYSIS_COMPLETED = "LANGUAGE_ANALYSIS_COMPLETED"
    NORMALIZATION_STARTED = "NORMALIZATION_STARTED"
    NORMALIZATION_COMPLETED = "NORMALIZATION_COMPLETED"
    TRANSLITERATION_STARTED = "TRANSLITERATION_STARTED"
    TRANSLITERATION_COMPLETED = "TRANSLITERATION_COMPLETED"
    TRANSLITERATION_SKIPPED = "TRANSLITERATION_SKIPPED"
    TRANSLITERATION_FAILED = "TRANSLITERATION_FAILED"
    TYPO_CODE_MIX_STARTED = "TYPO_CODE_MIX_STARTED"
    TYPO_CODE_MIX_COMPLETED = "TYPO_CODE_MIX_COMPLETED"
    TYPO_CODE_MIX_FAILED = "TYPO_CODE_MIX_FAILED"
    NUMBER_ROLES_STARTED = "NUMBER_ROLES_STARTED"
    NUMBER_ROLES_COMPLETED = "NUMBER_ROLES_COMPLETED"
    NUMBER_ROLES_FAILED = "NUMBER_ROLES_FAILED"
    DOMAIN_LEXICON_STARTED = "DOMAIN_LEXICON_STARTED"
    DOMAIN_LEXICON_COMPLETED = "DOMAIN_LEXICON_COMPLETED"
    DOMAIN_LEXICON_FAILED = "DOMAIN_LEXICON_FAILED"
    RESPONSE_REGISTER_STARTED = "RESPONSE_REGISTER_STARTED"
    RESPONSE_REGISTER_COMPLETED = "RESPONSE_REGISTER_COMPLETED"
    RESPONSE_REGISTER_FAILED = "RESPONSE_REGISTER_FAILED"
    OBJECT_REFERENCE_STARTED = "OBJECT_REFERENCE_STARTED"
    OBJECT_REFERENCE_COMPLETED = "OBJECT_REFERENCE_COMPLETED"
    OBJECT_REFERENCE_FAILED = "OBJECT_REFERENCE_FAILED"
    TURN_RELATION_STARTED = "TURN_RELATION_STARTED"
    TURN_RELATION_COMPLETED = "TURN_RELATION_COMPLETED"
    TURN_RELATION_FAILED = "TURN_RELATION_FAILED"
    REFERENCE_COREFERENCE_STARTED = "REFERENCE_COREFERENCE_STARTED"
    REFERENCE_COREFERENCE_COMPLETED = "REFERENCE_COREFERENCE_COMPLETED"
    REFERENCE_COREFERENCE_FAILED = "REFERENCE_COREFERENCE_FAILED"
    CONTEXT_ASSEMBLY_STARTED = "CONTEXT_ASSEMBLY_STARTED"
    CONTEXT_ASSEMBLY_COMPLETED = "CONTEXT_ASSEMBLY_COMPLETED"
    CONTEXT_ASSEMBLY_FAILED = "CONTEXT_ASSEMBLY_FAILED"
    ROUTING_STARTED = "ROUTING_STARTED"
    ROUTING_COMPLETED = "ROUTING_COMPLETED"
    ROUTING_FAILED = "ROUTING_FAILED"
    EVENT_SPEC_REGISTRY_STARTED = "EVENT_SPEC_REGISTRY_STARTED"
    EVENT_SPEC_REGISTRY_COMPLETED = "EVENT_SPEC_REGISTRY_COMPLETED"
    EVENT_SPEC_REGISTRY_FAILED = "EVENT_SPEC_REGISTRY_FAILED"
    EVENT_FRAME_EXTRACTION_STARTED = "EVENT_FRAME_EXTRACTION_STARTED"
    EVENT_FRAME_EXTRACTION_COMPLETED = "EVENT_FRAME_EXTRACTION_COMPLETED"
    EVENT_FRAME_EXTRACTION_FAILED = "EVENT_FRAME_EXTRACTION_FAILED"
    PLANNING_STARTED = "PLANNING_STARTED"
    PLANNING_COMPLETED = "PLANNING_COMPLETED"
    MODEL_REQUEST_STARTED = "MODEL_REQUEST_STARTED"
    MODEL_REQUEST_COMPLETED = "MODEL_REQUEST_COMPLETED"
    TOOL_CALL_STARTED = "TOOL_CALL_STARTED"
    TOOL_CALL_COMPLETED = "TOOL_CALL_COMPLETED"
    KNOWLEDGE_RETRIEVAL_STARTED = "KNOWLEDGE_RETRIEVAL_STARTED"
    KNOWLEDGE_RETRIEVAL_COMPLETED = "KNOWLEDGE_RETRIEVAL_COMPLETED"
    EVIDENCE_ASSEMBLY_COMPLETED = "EVIDENCE_ASSEMBLY_COMPLETED"
    RESPONSE_VALIDATION_STARTED = "RESPONSE_VALIDATION_STARTED"
    RESPONSE_VALIDATION_COMPLETED = "RESPONSE_VALIDATION_COMPLETED"
    SSE_STREAM_STARTED = "SSE_STREAM_STARTED"
    SSE_STREAM_COMPLETED = "SSE_STREAM_COMPLETED"
    DRAFT_TRANSITION = "DRAFT_TRANSITION"
    PREVIEW_GENERATED = "PREVIEW_GENERATED"
    CONFIRMATION_EVALUATED = "CONFIRMATION_EVALUATED"
    ACTION_DISPATCH_STARTED = "ACTION_DISPATCH_STARTED"
    ACTION_DISPATCH_COMPLETED = "ACTION_DISPATCH_COMPLETED"
    SYNC_STARTED = "SYNC_STARTED"
    SYNC_COMPLETED = "SYNC_COMPLETED"
    REQUEST_COMPLETED = "REQUEST_COMPLETED"
    REQUEST_FAILED = "REQUEST_FAILED"
    REQUEST_CANCELLED = "REQUEST_CANCELLED"


class TraceStatus(str, Enum):
    STARTED = "STARTED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    BLOCKED = "BLOCKED"
    DEGRADED = "DEGRADED"


# Stages that are active for Orbix ingress path today (others registered for later MAI).
ACTIVE_ORBIT_STAGES: frozenset[TraceStage] = frozenset(
    {
        TraceStage.GATEWAY_RECEIVED,
        TraceStage.AUTHENTICATION_RESOLVED,
        TraceStage.TENANT_SCOPE_VALIDATED,
        TraceStage.CONSTITUTION_POLICY_EVALUATED,
        TraceStage.CLIENT_CONTRACT_VALIDATED,
        TraceStage.CANONICAL_REQUEST_BUILT,
        TraceStage.ORCHESTRATOR_STARTED,
        TraceStage.DETERMINISTIC_PREPROCESS_STARTED,
        TraceStage.DETERMINISTIC_PREPROCESS_COMPLETED,
        TraceStage.MODEL_REQUEST_STARTED,
        TraceStage.MODEL_REQUEST_COMPLETED,
        TraceStage.RESPONSE_VALIDATION_STARTED,
        TraceStage.RESPONSE_VALIDATION_COMPLETED,
        TraceStage.SSE_STREAM_STARTED,
        TraceStage.SSE_STREAM_COMPLETED,
        TraceStage.CONFIRMATION_EVALUATED,
        TraceStage.REQUEST_COMPLETED,
        TraceStage.REQUEST_FAILED,
        TraceStage.REQUEST_CANCELLED,
    }
)


TERMINAL_STAGES: frozenset[TraceStage] = frozenset(
    {
        TraceStage.REQUEST_COMPLETED,
        TraceStage.REQUEST_FAILED,
        TraceStage.REQUEST_CANCELLED,
    }
)


def assert_known_stage(stage: str | TraceStage) -> TraceStage:
    if isinstance(stage, TraceStage):
        return stage
    try:
        return TraceStage(stage)
    except ValueError as exc:
        raise ValueError(f"UNKNOWN_TRACE_STAGE:{stage}") from exc
