"""MAI-06 lossless normalization package — derived views only; never mutates raw."""

from __future__ import annotations

NORMALIZER_VERSION = "mai-06.1.1"
RESOURCE_PACK_VERSION = "mai-06.1.0"
OFFSET_UNIT = "UNICODE_CODE_POINT"
MAX_INPUT_CODEPOINTS = 20000
MAX_EDITS = 5000
INTEGRITY_ALGORITHM = "SHA-256"
INTEGRITY_DOMAIN = "MOKXYA_NORMALIZATION_RECONSTRUCTION_V1"
INTEGRITY_SCHEMA_VERSION = "1.0.0"

__all__ = [
    "NORMALIZER_VERSION",
    "RESOURCE_PACK_VERSION",
    "OFFSET_UNIT",
    "MAX_INPUT_CODEPOINTS",
    "MAX_EDITS",
    "INTEGRITY_ALGORITHM",
    "INTEGRITY_DOMAIN",
    "INTEGRITY_SCHEMA_VERSION",
]
