"""Script and language-form taxonomies (MAI-05)."""

from __future__ import annotations

from enum import Enum


class ScriptCategory(str, Enum):
    DEVANAGARI = "DEVANAGARI"
    LATIN = "LATIN"
    ASCII_DIGIT = "ASCII_DIGIT"
    DEVANAGARI_DIGIT = "DEVANAGARI_DIGIT"
    COMMON_PUNCTUATION = "COMMON_PUNCTUATION"
    WHITESPACE = "WHITESPACE"
    SYMBOL = "SYMBOL"
    EMOJI = "EMOJI"
    CONTROL = "CONTROL"
    UNKNOWN = "UNKNOWN"
    MIXED = "MIXED"


class LanguageForm(str, Enum):
    NEPALI_DEVANAGARI = "NEPALI_DEVANAGARI"
    ROMANIZED_NEPALI = "ROMANIZED_NEPALI"
    ENGLISH = "ENGLISH"
    SHARED_OR_AMBIGUOUS_LATIN = "SHARED_OR_AMBIGUOUS_LATIN"
    TECHNICAL_ACCOUNTING_ENGLISH = "TECHNICAL_ACCOUNTING_ENGLISH"
    NAMED_ENTITY_CANDIDATE = "NAMED_ENTITY_CANDIDATE"
    IDENTIFIER_OR_CODE = "IDENTIFIER_OR_CODE"
    NUMERIC = "NUMERIC"
    PUNCTUATION_OR_SYMBOL = "PUNCTUATION_OR_SYMBOL"
    UNKNOWN = "UNKNOWN"


class ProtectedKind(str, Enum):
    URL = "URL"
    EMAIL = "EMAIL"
    PHONE_CANDIDATE = "PHONE_CANDIDATE"
    PAN_CANDIDATE = "PAN_CANDIDATE"
    VAT_IDENTIFIER = "VAT_IDENTIFIER"
    INVOICE_REFERENCE = "INVOICE_REFERENCE"
    VOUCHER_REFERENCE = "VOUCHER_REFERENCE"
    ACCOUNT_CODE = "ACCOUNT_CODE"
    PARTY_OR_MASTER_ID = "PARTY_OR_MASTER_ID"
    DOCUMENT_REFERENCE = "DOCUMENT_REFERENCE"
    LEGAL_CITATION = "LEGAL_CITATION"
    DATE_LITERAL = "DATE_LITERAL"
    TIME_LITERAL = "TIME_LITERAL"
    FISCAL_YEAR_LITERAL = "FISCAL_YEAR_LITERAL"
    MONEY_LITERAL = "MONEY_LITERAL"
    PERCENT_LITERAL = "PERCENT_LITERAL"
    DECIMAL_LITERAL = "DECIMAL_LITERAL"
    NUMBER_LITERAL = "NUMBER_LITERAL"
    FILE_PATH = "FILE_PATH"
    CODE_FRAGMENT = "CODE_FRAGMENT"
    JSON_FRAGMENT = "JSON_FRAGMENT"
    HASHTAG_OR_HANDLE = "HASHTAG_OR_HANDLE"
    USER_DECLARED_PROTECTED = "USER_DECLARED_PROTECTED"
    UNKNOWN_IDENTIFIER = "UNKNOWN_IDENTIFIER"


class InputQualityFlag(str, Enum):
    BIDI_CONTROL_PRESENT = "BIDI_CONTROL_PRESENT"
    ZERO_WIDTH_PRESENT = "ZERO_WIDTH_PRESENT"
    INVISIBLE_SEPARATOR_PRESENT = "INVISIBLE_SEPARATOR_PRESENT"
    CONTROL_CHARACTER_PRESENT = "CONTROL_CHARACTER_PRESENT"
    MIXED_SCRIPT_TOKEN = "MIXED_SCRIPT_TOKEN"
    CONFUSABLE_RISK = "CONFUSABLE_RISK"
    EXCESSIVE_LENGTH = "EXCESSIVE_LENGTH"
    EXCESSIVE_COMBINING_MARKS = "EXCESSIVE_COMBINING_MARKS"
    EXCESSIVE_REPETITION = "EXCESSIVE_REPETITION"
    MALFORMED_IDENTIFIER_CANDIDATE = "MALFORMED_IDENTIFIER_CANDIDATE"
    UNUSUAL_WHITESPACE = "UNUSUAL_WHITESPACE"


class CodeMixPattern(str, Enum):
    ENGLISH_ONLY = "ENGLISH_ONLY"
    NEPALI_DEVANAGARI_ONLY = "NEPALI_DEVANAGARI_ONLY"
    ROMANIZED_NEPALI_ONLY = "ROMANIZED_NEPALI_ONLY"
    ENGLISH_ROMANIZED = "ENGLISH_ROMANIZED"
    ENGLISH_DEVANAGARI = "ENGLISH_DEVANAGARI"
    DEVANAGARI_ROMANIZED = "DEVANAGARI_ROMANIZED"
    THREE_WAY_MIX = "THREE_WAY_MIX"
    MOSTLY_IDENTIFIERS = "MOSTLY_IDENTIFIERS"
    AMBIGUOUS = "AMBIGUOUS"
    UNKNOWN = "UNKNOWN"
