// AUTO-GENERATED by scripts/build-falcon-page-index.mjs — do not edit manually.
// Rebuilt on every `npm run build`. 101 screens indexed from App.tsx + page headers.

export interface GeneratedPageEntry {
  route: string;
  aliases: string[];
  component: string;
  file: string;
  title: string;
  subtitle: string;
  menuPath: string;
}

export const GENERATED_PAGE_INDEX: GeneratedPageEntry[] = [
  {
    "route": "accounts",
    "aliases": [
      "accounts",
      "chart-of-accounts"
    ],
    "component": "ChartOfAccounts",
    "file": "src/components/ChartOfAccounts.tsx",
    "title": "Chart of Accounts",
    "subtitle": "{allGroups.length} groups · {allLedgers.length} ledgers",
    "menuPath": "Masters → Chart of Accounts"
  },
  {
    "route": "accounts-configuration",
    "aliases": [
      "accounts-configuration"
    ],
    "component": "AccountsConfiguration",
    "file": "src/pages/AccountsConfiguration.tsx",
    "title": "Accounts Configuration",
    "subtitle": "Features &amp; Options — Accounts Settings",
    "menuPath": "Administration → Accounts Config"
  },
  {
    "route": "aging-report",
    "aliases": [
      "aging-report"
    ],
    "component": "AgingReport",
    "file": "src/pages/AgingReport.tsx",
    "title": "Aging Report",
    "subtitle": "Outstanding {direction === \"receivable\" ? \"receivables\" : \"payables\"} by age bucket",
    "menuPath": "Books & Reports → Aging Report"
  },
  {
    "route": "attendance-voucher",
    "aliases": [
      "attendance-voucher",
      "attendance-entry"
    ],
    "component": "PayrollRun",
    "file": "src/pages/PayrollRun.tsx",
    "title": "Payroll Run",
    "subtitle": "Process and manage employee payroll",
    "menuPath": ""
  },
  {
    "route": "audit-log",
    "aliases": [
      "audit-log"
    ],
    "component": "AuditLog",
    "file": "src/pages/AuditLog.tsx",
    "title": "Audit Log",
    "subtitle": "User activity, data change history, security access trail and compliance export.",
    "menuPath": "Administration → Audit Log"
  },
  {
    "route": "backup",
    "aliases": [
      "backup",
      "backup-restore"
    ],
    "component": "BackupRestore",
    "file": "src/pages/BackupRestore.tsx",
    "title": "Backup Restore",
    "subtitle": "Selected Tables",
    "menuPath": "Administration → Backup & Restore"
  },
  {
    "route": "balance-sheet",
    "aliases": [
      "balance-sheet"
    ],
    "component": "BalanceSheet",
    "file": "src/pages/BalanceSheet.tsx",
    "title": "Balance Sheet",
    "subtitle": "Group Detail · {options.fromDate} to {options.toDate} · {allRows.length} accounts",
    "menuPath": "Books & Reports → Balance Sheet"
  },
  {
    "route": "bank-book",
    "aliases": [
      "bank-book"
    ],
    "component": "BankBook",
    "file": "src/pages/BankBook.tsx",
    "title": "Bank Book",
    "subtitle": "",
    "menuPath": ""
  },
  {
    "route": "bank-reconciliation",
    "aliases": [
      "bank-reconciliation"
    ],
    "component": "BankReconciliation",
    "file": "src/pages/BankReconciliation.tsx",
    "title": "Bank Reconciliation",
    "subtitle": "",
    "menuPath": ""
  },
  {
    "route": "bank-statement-import",
    "aliases": [
      "bank-statement-import"
    ],
    "component": "BankStatementImport",
    "file": "src/pages/BankStatementImport.tsx",
    "title": "Bank Statement Import",
    "subtitle": "Upload Excel/CSV statement, preview rows, auto-match to vouchers and reconcile.",
    "menuPath": ""
  },
  {
    "route": "batch-management",
    "aliases": [
      "batch-management",
      "batches"
    ],
    "component": "BatchManagement",
    "file": "src/pages/BatchManagement.tsx",
    "title": "Batch &amp; Serial Number Tracking",
    "subtitle": "Track inventory by batch/lot or individual serial number",
    "menuPath": "Inventory → Batch Management"
  },
  {
    "route": "bill-sundry",
    "aliases": [
      "bill-sundry",
      "bill-sundries"
    ],
    "component": "BillSundryMaster",
    "file": "src/pages/BillSundryMaster.tsx",
    "title": "Bill Sundry Master",
    "subtitle": "Freight, discount, round off, packing and other charges",
    "menuPath": "Masters → Bill Sundries"
  },
  {
    "route": "billing",
    "aliases": [
      "billing",
      "sales-return"
    ],
    "component": "BillingInvoice",
    "file": "src/pages/BillingInvoice.tsx",
    "title": "Billing & invoicing",
    "subtitle": "Manage sales and purchase invoices and returns",
    "menuPath": "Transactions → Sales Invoice"
  },
  {
    "route": "bonus-provision",
    "aliases": [
      "bonus-provision"
    ],
    "component": "BonusProvision",
    "file": "src/pages/BonusProvision.tsx",
    "title": "Bonus Provision",
    "subtitle": "Compute bonus provision from net profit and eligible employees",
    "menuPath": ""
  },
  {
    "route": "budget",
    "aliases": [
      "budget"
    ],
    "component": "BudgetMaster",
    "file": "src/pages/BudgetMaster.tsx",
    "title": "Budget Master",
    "subtitle": "Set monthly or annual limits for income and expense accounts",
    "menuPath": "Masters → Budget Master"
  },
  {
    "route": "budget-vs-actual",
    "aliases": [
      "budget-vs-actual"
    ],
    "component": "BudgetVsActual",
    "file": "src/pages/BudgetVsActual.tsx",
    "title": "Budget Vs Actual",
    "subtitle": "",
    "menuPath": "Books & Reports → Budget vs Actual"
  },
  {
    "route": "cash-book",
    "aliases": [
      "cash-book"
    ],
    "component": "CashBook",
    "file": "src/pages/CashBook.tsx",
    "title": "Cash Book",
    "subtitle": "",
    "menuPath": ""
  },
  {
    "route": "cash-flow",
    "aliases": [
      "cash-flow"
    ],
    "component": "CashFlowStatement",
    "file": "src/pages/CashFlowStatement.tsx",
    "title": "Cash Flow Statement",
    "subtitle": "{companySettings?.name || \"Company\"} — {fromDate} to {toDate} •{\" \"}\n            {method === \"indirect\" ? \"Indirect Method (IAS 7)\" : \"Direct Method (IAS 7)\"}",
    "menuPath": "Books & Reports → Cash Flow"
  },
  {
    "route": "cheque-printing",
    "aliases": [
      "cheque-printing"
    ],
    "component": "ChequePrinting",
    "file": "src/pages/ChequePrinting.tsx",
    "title": "Cheque Printing",
    "subtitle": "",
    "menuPath": ""
  },
  {
    "route": "cheque-register",
    "aliases": [
      "cheque-register"
    ],
    "component": "ChequeRegister",
    "file": "src/pages/ChequeRegister.tsx",
    "title": "Cheque Register",
    "subtitle": "",
    "menuPath": ""
  },
  {
    "route": "communication-hub",
    "aliases": [
      "communication-hub",
      "communication"
    ],
    "component": "CommunicationHub",
    "file": "src/pages/CommunicationHub.tsx",
    "title": "Communication Hub",
    "subtitle": "Invoice delivery, payment reminders and external data import utilities.",
    "menuPath": "Administration → Communication Hub"
  },
  {
    "route": "configuration-hub",
    "aliases": [
      "configuration-hub",
      "configuration",
      "holidays"
    ],
    "component": "ConfigurationHub",
    "file": "src/pages/ConfigurationHub.tsx",
    "title": "List of Holidays",
    "subtitle": "Applies to accounting and inventory vouchers when saving new entries.",
    "menuPath": "Administration → Configuration Hub"
  },
  {
    "route": "contra",
    "aliases": [
      "contra"
    ],
    "component": "ContraVoucher",
    "file": "src/pages/ContraVoucher.tsx",
    "title": "Contra Voucher",
    "subtitle": "{fromAcct?.name} → {toAcct?.name}",
    "menuPath": "Transactions → Contra"
  },
  {
    "route": "cost-centers",
    "aliases": [
      "cost-centers",
      "cost-centre"
    ],
    "component": "CostCenters",
    "file": "src/pages/CostCenters.tsx",
    "title": "Cost Centers",
    "subtitle": "Manage hierarchical cost centers, departments, and branches",
    "menuPath": "Masters → Cost Centers"
  },
  {
    "route": "credit-note",
    "aliases": [
      "credit-note"
    ],
    "component": "CreditNoteVoucher",
    "file": "src/pages/CreditNoteVoucher.tsx",
    "title": "Credit Note Voucher",
    "subtitle": "",
    "menuPath": "Transactions → Credit Note"
  },
  {
    "route": "data-import-export",
    "aliases": [
      "data-import-export",
      "data-export-import"
    ],
    "component": "DataExportImport",
    "file": "src/pages/DataExportImport.tsx",
    "title": "Data Export Import",
    "subtitle": "",
    "menuPath": ""
  },
  {
    "route": "day-book",
    "aliases": [
      "day-book"
    ],
    "component": "DayBook",
    "file": "src/pages/DayBook.tsx",
    "title": "Day Book",
    "subtitle": "All vouchers and transactions for a selected date",
    "menuPath": "Books & Reports → Day Book"
  },
  {
    "route": "debit-note",
    "aliases": [
      "debit-note"
    ],
    "component": "DebitNoteVoucher",
    "file": "src/pages/DebitNoteVoucher.tsx",
    "title": "Debit Note Voucher",
    "subtitle": "",
    "menuPath": "Transactions → Debit Note"
  },
  {
    "route": "delivery-challan",
    "aliases": [
      "delivery-challan"
    ],
    "component": "DeliveryChallan",
    "file": "src/pages/DeliveryChallan.tsx",
    "title": "Delivery Challan",
    "subtitle": "",
    "menuPath": "Transactions → Delivery Challan"
  },
  {
    "route": "employee-loans",
    "aliases": [
      "employee-loans"
    ],
    "component": "EmployeeLoans",
    "file": "src/pages/EmployeeLoans.tsx",
    "title": "Employee Loans",
    "subtitle": "",
    "menuPath": ""
  },
  {
    "route": "employees",
    "aliases": [
      "employees",
      "employee-master"
    ],
    "component": "EmployeeMaster",
    "file": "src/pages/EmployeeMaster.tsx",
    "title": "Employee Master",
    "subtitle": "Manage staff, designations, and payroll details",
    "menuPath": ""
  },
  {
    "route": "equity-statement",
    "aliases": [
      "equity-statement"
    ],
    "component": "EquityStatement",
    "file": "src/pages/EquityStatement.tsx",
    "title": "Statement of Changes in Equity",
    "subtitle": "{companySettings?.name || \"Company\"} — {fromDate} to {toDate} • NFRS Compliant",
    "menuPath": ""
  },
  {
    "route": "financial-dashboard",
    "aliases": [
      "financial-dashboard",
      "dashboard"
    ],
    "component": "FinancialDashboard",
    "file": "src/pages/FinancialDashboard.tsx",
    "title": "Dashboard",
    "subtitle": "{bsDateStr} · {adDateStr}",
    "menuPath": "Home → Financial Dashboard"
  },
  {
    "route": "fiscal-year",
    "aliases": [
      "fiscal-year"
    ],
    "component": "FiscalYear",
    "file": "src/pages/FiscalYear.tsx",
    "title": "Fiscal Year Management",
    "subtitle": "",
    "menuPath": "Masters → Fiscal Year"
  },
  {
    "route": "fixed-assets",
    "aliases": [
      "fixed-assets"
    ],
    "component": "FixedAssets",
    "file": "src/pages/FixedAssets.tsx",
    "title": "Fixed Assets Register",
    "subtitle": "{companySettings?.name || \"Company\"} — Nepal IT Act Depreciation",
    "menuPath": "Masters → Fixed Assets"
  },
  {
    "route": "funds-flow",
    "aliases": [
      "funds-flow",
      "funds-flow-statement"
    ],
    "component": "FundsFlowStatement",
    "file": "src/pages/FundsFlowStatement.tsx",
    "title": "Funds Flow Statement",
    "subtitle": "",
    "menuPath": ""
  },
  {
    "route": "goods-receipt",
    "aliases": [
      "goods-receipt",
      "grn"
    ],
    "component": "GoodsReceiptNote",
    "file": "src/pages/GoodsReceiptNote.tsx",
    "title": "Goods Receipt Note",
    "subtitle": "",
    "menuPath": "Transactions → Goods Receipt Note"
  },
  {
    "route": "gratuity-calculation",
    "aliases": [
      "gratuity-calculation"
    ],
    "component": "GratuityCalculation",
    "file": "src/pages/GratuityCalculation.tsx",
    "title": "Gratuity Calculation",
    "subtitle": "Labour Act 2074 — 8.33% of basic salary per year of service",
    "menuPath": ""
  },
  {
    "route": "income-expenditure",
    "aliases": [
      "income-expenditure"
    ],
    "component": "IncomeExpenditureAccount",
    "file": "src/pages/IncomeExpenditureAccount.tsx",
    "title": "Income Expenditure Account",
    "subtitle": "",
    "menuPath": "Books & Reports → Income & Expenditure"
  },
  {
    "route": "interest-calculation",
    "aliases": [
      "interest-calculation"
    ],
    "component": "InterestCalculation",
    "file": "src/pages/InterestCalculation.tsx",
    "title": "Interest Calculation",
    "subtitle": "Calculate overdue interest on outstanding{\" \"}\n            {direction === \"receivable\" ? \"receivables\" : \"payables\"}",
    "menuPath": "Books & Reports → Interest Calculation"
  },
  {
    "route": "inventory-config",
    "aliases": [
      "inventory-config",
      "inventory-configuration"
    ],
    "component": "InventoryConfiguration",
    "file": "src/pages/InventoryConfiguration.tsx",
    "title": "Inventory Configuration",
    "subtitle": "Configure inventory features and behavior",
    "menuPath": "Administration → Inventory Config"
  },
  {
    "route": "item-groups",
    "aliases": [
      "item-groups",
      "item-group-master"
    ],
    "component": "ItemGroupMaster",
    "file": "src/pages/ItemGroupMaster.tsx",
    "title": "Item Groups",
    "subtitle": "Group stock items for reporting, defaults, and tax mapping",
    "menuPath": "Inventory → Item Groups"
  },
  {
    "route": "item-master",
    "aliases": [
      "item-master",
      "items",
      "stock-book"
    ],
    "component": "StockBook",
    "file": "src/pages/StockBook.tsx",
    "title": "Stock Ledger",
    "subtitle": "Item-wise movement history with {methodLabel.toLowerCase()} valuation",
    "menuPath": "Inventory → Item Master"
  },
  {
    "route": "job-work-register",
    "aliases": [
      "job-work-register",
      "job-work-out-order",
      "job-work-in-order"
    ],
    "component": "JobWorkRegister",
    "file": "src/pages/JobWorkRegister.tsx",
    "title": "Job Work Register",
    "subtitle": "",
    "menuPath": ""
  },
  {
    "route": "journal",
    "aliases": [
      "journal"
    ],
    "component": "JournalEntries",
    "file": "src/pages/JournalEntries.tsx",
    "title": "Journal vouchers",
    "subtitle": "Double-entry journal voucher register",
    "menuPath": "Transactions → Journal"
  },
  {
    "route": "ledger-report",
    "aliases": [
      "ledger-report",
      "ledger"
    ],
    "component": "GeneralLedger",
    "file": "src/pages/GeneralLedger.tsx",
    "title": "{companySettings?.companyNameEn || companySettings?.name || \"Company\"}",
    "subtitle": "",
    "menuPath": "Books & Reports → General Ledger"
  },
  {
    "route": "ledgers",
    "aliases": [
      "ledgers",
      "ledger-master"
    ],
    "component": "LedgerMaster",
    "file": "src/pages/LedgerMaster.tsx",
    "title": "Ledger Master",
    "subtitle": "Manage accounts and ledgers",
    "menuPath": ""
  },
  {
    "route": "master-control-centre",
    "aliases": [
      "master-control-centre"
    ],
    "component": "MasterControlCentre",
    "file": "src/pages/MasterControlCentre.tsx",
    "title": "Master Control Centre",
    "subtitle": "",
    "menuPath": ""
  },
  {
    "route": "material-issued",
    "aliases": [
      "material-issued",
      "material-out"
    ],
    "component": "MaterialIssuedPage",
    "file": "src/pages/MaterialIssuedPage.tsx",
    "title": "Material Issued Page",
    "subtitle": "Total Entries: {materialIssued?.length || 0}",
    "menuPath": ""
  },
  {
    "route": "material-received",
    "aliases": [
      "material-received",
      "material-in"
    ],
    "component": "MaterialReceivedPage",
    "file": "src/pages/MaterialReceivedPage.tsx",
    "title": "Material Received Page",
    "subtitle": "Total Entries: {materialReceived?.length || 0}",
    "menuPath": ""
  },
  {
    "route": "misc-masters",
    "aliases": [
      "misc-masters",
      "material-centres",
      "bill-of-material",
      "bom"
    ],
    "component": "MiscMasters",
    "file": "src/pages/MiscMasters.tsx",
    "title": "Misc Masters",
    "subtitle": "Material centres (warehouses), bill of materials, price lists",
    "menuPath": ""
  },
  {
    "route": "notes-to-accounts",
    "aliases": [
      "notes-to-accounts"
    ],
    "component": "NotesToAccounts",
    "file": "src/pages/NotesToAccounts.tsx",
    "title": "Notes To Accounts",
    "subtitle": "",
    "menuPath": ""
  },
  {
    "route": "outstanding-payables",
    "aliases": [
      "outstanding-payables"
    ],
    "component": "OutstandingPayables",
    "file": "src/pages/OutstandingPayables.tsx",
    "title": "Outstanding Payables",
    "subtitle": "Unpaid and partially paid sales invoices",
    "menuPath": "Books & Reports → Outstanding Payables"
  },
  {
    "route": "outstanding-receivables",
    "aliases": [
      "outstanding-receivables"
    ],
    "component": "OutstandingReceivables",
    "file": "src/pages/OutstandingReceivables.tsx",
    "title": "Outstanding Receivables",
    "subtitle": "Unpaid and partially paid sales invoices",
    "menuPath": "Books & Reports → Outstanding Receivables"
  },
  {
    "route": "parties",
    "aliases": [
      "parties",
      "party-master"
    ],
    "component": "Parties",
    "file": "src/pages/Parties.tsx",
    "title": "Parties Directory",
    "subtitle": "Manage your customers, suppliers, and their financial ledgers",
    "menuPath": "Masters → Parties"
  },
  {
    "route": "party-statement",
    "aliases": [
      "party-statement"
    ],
    "component": "PartyLedgerStatement",
    "file": "src/pages/PartyLedgerStatement.tsx",
    "title": "Party Ledger",
    "subtitle": "Transaction history for a specific party",
    "menuPath": "Books & Reports → Party Statement"
  },
  {
    "route": "pay-heads",
    "aliases": [
      "pay-heads"
    ],
    "component": "PayHeadMaster",
    "file": "src/pages/PayHeadMaster.tsx",
    "title": "Pay Head Master",
    "subtitle": "Manage earnings, deductions, and statutory pay components",
    "menuPath": ""
  },
  {
    "route": "payment",
    "aliases": [
      "payment"
    ],
    "component": "PaymentVoucher",
    "file": "src/pages/PaymentVoucher.tsx",
    "title": "Payment vouchers",
    "subtitle": "Cash and bank payments — expenses, suppliers, and transfers",
    "menuPath": "Transactions → Payment"
  },
  {
    "route": "payroll",
    "aliases": [
      "payroll",
      "salary-process"
    ],
    "component": "Payroll",
    "file": "src/pages/Payroll.tsx",
    "title": "Payroll",
    "subtitle": "",
    "menuPath": "Masters → Payroll"
  },
  {
    "route": "pdc-register",
    "aliases": [
      "pdc-register"
    ],
    "component": "PDCRegister",
    "file": "src/pages/PDCRegister.tsx",
    "title": "P D C Register",
    "subtitle": "",
    "menuPath": ""
  },
  {
    "route": "pdc-summary",
    "aliases": [
      "pdc-summary",
      "pdc-management"
    ],
    "component": "PDCManagement",
    "file": "src/pages/PDCManagement.tsx",
    "title": "Post-Dated Cheque (PDC) Management",
    "subtitle": "Track cheques received from customers and issued to suppliers",
    "menuPath": "Masters → PDC Management"
  },
  {
    "route": "physical-stock",
    "aliases": [
      "physical-stock"
    ],
    "component": "PhysicalStockPage2",
    "file": "src/pages/PhysicalStockPage2.tsx",
    "title": "Physical Stock Voucher",
    "subtitle": "Record actual physical stock count — system auto-generates Stock Journal for variances",
    "menuPath": "Inventory → Physical Stock"
  },
  {
    "route": "price-lists",
    "aliases": [
      "price-lists",
      "price-list-master"
    ],
    "component": "PriceLists",
    "file": "src/pages/PriceLists.tsx",
    "title": "Price Lists",
    "subtitle": "Define item-specific pricing for customers",
    "menuPath": "Masters → Price Lists"
  },
  {
    "route": "production",
    "aliases": [
      "production"
    ],
    "component": "ProductionPage",
    "file": "src/pages/ProductionPage.tsx",
    "title": "Production Page",
    "subtitle": "Total Entries: {productions?.length || 0}",
    "menuPath": ""
  },
  {
    "route": "profit-loss",
    "aliases": [
      "profit-loss"
    ],
    "component": "ProfitLoss",
    "file": "src/pages/ProfitLoss.tsx",
    "title": "Profit Loss",
    "subtitle": "",
    "menuPath": "Books & Reports → Profit & Loss"
  },
  {
    "route": "purchase",
    "aliases": [
      "purchase",
      "purchase-return"
    ],
    "component": "PurchaseVoucher",
    "file": "src/pages/PurchaseVoucher.tsx",
    "title": "Purchase Invoice",
    "subtitle": "Create and manage purchase invoices with TDS",
    "menuPath": "Transactions → Purchase Invoice"
  },
  {
    "route": "purchase-register",
    "aliases": [
      "purchase-register"
    ],
    "component": "PurchaseRegister",
    "file": "src/pages/PurchaseRegister.tsx",
    "title": "Purchase register",
    "subtitle": "All purchase invoices and returns",
    "menuPath": ""
  },
  {
    "route": "purchase-type",
    "aliases": [
      "purchase-type",
      "purchase-types"
    ],
    "component": "PurchaseTypeMaster",
    "file": "src/pages/PurchaseTypeMaster.tsx",
    "title": "Purchase Type Master",
    "subtitle": "Configure purchase types: local GST, central GST, RCM/unregistered, etc.",
    "menuPath": ""
  },
  {
    "route": "quotation",
    "aliases": [
      "quotation",
      "sales-quotation",
      "purchase-quotation"
    ],
    "component": "QuotationPage",
    "file": "src/pages/QuotationPage.tsx",
    "title": "{editQuotation ? \"Modify\" : \"Add\"} {title}",
    "subtitle": "Manage quotations — convert accepted quotations to{\" \"}\n            {isSales ? \"sales orders / invoices\" : \"purchase orders\"} via F11",
    "menuPath": ""
  },
  {
    "route": "ratio-analysis",
    "aliases": [
      "ratio-analysis"
    ],
    "component": "RatioAnalysis",
    "file": "src/pages/RatioAnalysis.tsx",
    "title": "Ratio Analysis",
    "subtitle": "Key financial indicators and metrics",
    "menuPath": "Books & Reports → Ratio Analysis"
  },
  {
    "route": "receipt",
    "aliases": [
      "receipt"
    ],
    "component": "ReceiptVoucher",
    "file": "src/pages/ReceiptVoucher.tsx",
    "title": "Receipt vouchers",
    "subtitle": "Cash and bank receipts — customer payments, income, and deposits",
    "menuPath": "Transactions → Receipt"
  },
  {
    "route": "recurring-vouchers",
    "aliases": [
      "recurring-vouchers"
    ],
    "component": "RecurringVouchers",
    "file": "src/pages/RecurringVouchers.tsx",
    "title": "Recurring Vouchers",
    "subtitle": "",
    "menuPath": "Administration → Recurring Vouchers"
  },
  {
    "route": "rejection-out",
    "aliases": [
      "rejection-out",
      "rejection-in"
    ],
    "component": "RejectionVoucherPage",
    "file": "src/pages/RejectionVoucherPage.tsx",
    "title": "{title}",
    "subtitle": "Total Entries: {entries.length}",
    "menuPath": ""
  },
  {
    "route": "reversing-journals",
    "aliases": [
      "reversing-journals",
      "reversing-journal"
    ],
    "component": "ReversingJournals",
    "file": "src/pages/ReversingJournals.tsx",
    "title": "Reversing Journals",
    "subtitle": "Manage and automate reversing journal entries",
    "menuPath": ""
  },
  {
    "route": "sale-type",
    "aliases": [
      "sale-type",
      "sale-types"
    ],
    "component": "SaleTypeMaster",
    "file": "src/pages/SaleTypeMaster.tsx",
    "title": "Sale Type Master",
    "subtitle": "Configure sale types: local GST, central GST, export, itemwise, etc.",
    "menuPath": ""
  },
  {
    "route": "sales",
    "aliases": [
      "sales"
    ],
    "component": "SalesVoucher",
    "file": "src/pages/SalesVoucher.tsx",
    "title": "Sales Invoice",
    "subtitle": "Create and manage sales invoices",
    "menuPath": ""
  },
  {
    "route": "sales-analysis",
    "aliases": [
      "sales-analysis"
    ],
    "component": "SalesAnalysisReport",
    "file": "src/pages/SalesAnalysisReport.tsx",
    "title": "Sales Analysis Report",
    "subtitle": "Party turnover, item-wise sales, month-wise trends and purchase analysis",
    "menuPath": ""
  },
  {
    "route": "sales-order",
    "aliases": [
      "sales-order",
      "purchase-order"
    ],
    "component": "OrderVoucherPage",
    "file": "src/pages/OrderVoucherPage.tsx",
    "title": "{editOrder ? \"Modify\" : \"Add\"} {title}",
    "subtitle": "Manage {title.toLowerCase()}s — pick into{\" \"}\n            {isSalesOrder ? \"sales/delivery challans\" : \"purchase/GRNs\"} via F11",
    "menuPath": "Transactions → Sales Order"
  },
  {
    "route": "sales-persons",
    "aliases": [
      "sales-persons"
    ],
    "component": "SalesPersons",
    "file": "src/pages/SalesPersons.tsx",
    "title": "Sales Persons",
    "subtitle": "Manage your sales team members and commission rates",
    "menuPath": ""
  },
  {
    "route": "sales-register",
    "aliases": [
      "sales-register"
    ],
    "component": "SalesRegister",
    "file": "src/pages/SalesRegister.tsx",
    "title": "Sales register",
    "subtitle": "All sales invoices and returns",
    "menuPath": ""
  },
  {
    "route": "schemes",
    "aliases": [
      "schemes"
    ],
    "component": "SchemeMaster",
    "file": "src/pages/SchemeMaster.tsx",
    "title": "Scheme / Offer Master",
    "subtitle": "Configure promotional schemes, discounts, and offers for items and parties",
    "menuPath": ""
  },
  {
    "route": "settings",
    "aliases": [
      "settings",
      "company-settings"
    ],
    "component": "CompanySettings",
    "file": "src/pages/CompanySettings.tsx",
    "title": "Company Settings",
    "subtitle": "",
    "menuPath": ""
  },
  {
    "route": "standard-narration",
    "aliases": [
      "standard-narration",
      "standard-narrations"
    ],
    "component": "StandardNarrationMaster",
    "file": "src/pages/StandardNarrationMaster.tsx",
    "title": "Standard Narration Master",
    "subtitle": "Pre-defined narrations — press F4 in vouchers to pick from list",
    "menuPath": "Masters → Narrations"
  },
  {
    "route": "stock-journal",
    "aliases": [
      "stock-journal"
    ],
    "component": "StockJournalPage",
    "file": "src/pages/StockJournalPage.tsx",
    "title": "Stock Journal Page",
    "subtitle": "",
    "menuPath": "Inventory → Stock Journal"
  },
  {
    "route": "stock-ledger",
    "aliases": [
      "stock-ledger"
    ],
    "component": "StockLedgerReport",
    "file": "src/pages/StockLedgerReport.tsx",
    "title": "Stock ledger report",
    "subtitle": "Item-wise movement history with running balance (IN/OUT transactions)",
    "menuPath": "Inventory → Stock Ledger"
  },
  {
    "route": "stock-status",
    "aliases": [
      "stock-status",
      "closing-stock",
      "inventory-report"
    ],
    "component": "InventoryReport",
    "file": "src/pages/InventoryReport.tsx",
    "title": "Inventory Report",
    "subtitle": "",
    "menuPath": ""
  },
  {
    "route": "stock-summary",
    "aliases": [
      "stock-summary"
    ],
    "component": "StockSummaryReport",
    "file": "src/pages/StockSummaryReport.tsx",
    "title": "Stock Summary Report",
    "subtitle": "Closing stock — {valuationMethod.toUpperCase().replace(\"_\", \" \")} valuation",
    "menuPath": "Inventory → Stock Summary"
  },
  {
    "route": "stock-transfer",
    "aliases": [
      "stock-transfer"
    ],
    "component": "StockTransfer",
    "file": "src/pages/StockTransfer.tsx",
    "title": "Stock Transfer Voucher",
    "subtitle": "Inter-godown / inter-branch material transfer",
    "menuPath": "Inventory → Stock Transfer"
  },
  {
    "route": "tax-category",
    "aliases": [
      "tax-category",
      "tax-categories"
    ],
    "component": "TaxCategoryMaster",
    "file": "src/pages/TaxCategoryMaster.tsx",
    "title": "Tax Category Master",
    "subtitle": "GST 5%, 12%, 18%, 28%, VAT 13%, NIL, exempt tax categories",
    "menuPath": ""
  },
  {
    "route": "tds-certificate",
    "aliases": [
      "tds-certificate"
    ],
    "component": "TdsCertificatePage",
    "file": "src/pages/TdsCertificatePage.tsx",
    "title": "Tds Certificate Page",
    "subtitle": "Generate certificate of tax deduction at source for deductees",
    "menuPath": ""
  },
  {
    "route": "tds-report",
    "aliases": [
      "tds-report",
      "tds-reports"
    ],
    "component": "TdsReport",
    "file": "src/pages/TdsReport.tsx",
    "title": "TDS register",
    "subtitle": "Section-wise TDS records for Income Tax Act 2058",
    "menuPath": ""
  },
  {
    "route": "trial-balance",
    "aliases": [
      "trial-balance"
    ],
    "component": "TrialBalance",
    "file": "src/pages/TrialBalance.tsx",
    "title": "Trial Balance",
    "subtitle": "{options.fromDate} to {options.toDate}",
    "menuPath": "Books & Reports → Trial Balance"
  },
  {
    "route": "unassemble",
    "aliases": [
      "unassemble"
    ],
    "component": "UnassemblePage",
    "file": "src/pages/UnassemblePage.tsx",
    "title": "Unassemble Page",
    "subtitle": "Total Entries: {unassembles?.length || 0}",
    "menuPath": ""
  },
  {
    "route": "unit-conversion",
    "aliases": [
      "unit-conversion",
      "unit-conversions"
    ],
    "component": "UnitConversionMaster",
    "file": "src/pages/UnitConversionMaster.tsx",
    "title": "Unit Conversions",
    "subtitle": "Manage relationships and conversion factors between units",
    "menuPath": ""
  },
  {
    "route": "units",
    "aliases": [
      "units"
    ],
    "component": "Units",
    "file": "src/pages/Units.tsx",
    "title": "Units of Measure",
    "subtitle": "Manage measurement units used for stock items (kg, pcs, ltr, etc.)",
    "menuPath": "Masters → Units"
  },
  {
    "route": "users",
    "aliases": [
      "users",
      "users-management"
    ],
    "component": "UsersManagement",
    "file": "src/pages/UsersManagement.tsx",
    "title": "Users Management",
    "subtitle": "Field-level permissions, branch isolation, login audit and security policies",
    "menuPath": "Administration → Users"
  },
  {
    "route": "vat-classifications",
    "aliases": [
      "vat-classifications"
    ],
    "component": "VATClassificationMaster",
    "file": "src/pages/VATClassificationMaster.tsx",
    "title": "VAT Classification Master (Nepal)",
    "subtitle": "Manage tax classifications and nature of transactions",
    "menuPath": ""
  },
  {
    "route": "vat-reports",
    "aliases": [
      "vat-reports",
      "gstr1",
      "gstr2",
      "gstr3b",
      "gst-summary"
    ],
    "component": "VatReports",
    "file": "src/pages/VatReports.tsx",
    "title": "{title}",
    "subtitle": "{subtitle}",
    "menuPath": "Books & Reports → VAT Reports"
  },
  {
    "route": "voucher-entry",
    "aliases": [
      "voucher-entry"
    ],
    "component": "VoucherEntryHub",
    "file": "src/pages/VoucherEntryHub.tsx",
    "title": "Voucher Entry Hub",
    "subtitle": "",
    "menuPath": "Transactions → Voucher Entry Hub"
  },
  {
    "route": "voucher-types",
    "aliases": [
      "voucher-types",
      "voucher-series-config"
    ],
    "component": "VoucherTypeMaster",
    "file": "src/pages/VoucherTypeMaster.tsx",
    "title": "Voucher Series Configuration",
    "subtitle": "Numbering, features, settlement, and round-off per voucher type and series",
    "menuPath": ""
  },
  {
    "route": "warehouses",
    "aliases": [
      "warehouses"
    ],
    "component": "Warehouses",
    "file": "src/pages/Warehouses.tsx",
    "title": "Warehouses / Go-downs",
    "subtitle": "Manage stock locations and go-downs for inventory tracking",
    "menuPath": "Inventory → Warehouses"
  }
];

export const GENERATED_PAGE_INDEX_BUILT_AT = "2026-07-04T09:46:35.473Z";
